# Generated by Django 5.2.9 on 2026-02-12 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_add_payment_model'),
        ('general', '0020_backfill_session_mentors_from_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='general.session'),
        ),
    ]
