# Generated by Django 5.2.3 on 2026-02-12 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_mentorprofile_wallet_balance_cents'),
        ('billing', '0003_payment_mentor_nullable_and_wallet_transaction'),
        ('general', '0022_session_paid_out_at_alter_session_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='accounts.mentorprofile')),
                ('related_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_wallet_transactions', to='billing.payment')),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_wallet_transactions', to='general.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
