# Generated by Django 5.2.3 on 2026-01-18 12:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Mindset', 'Trading', 'Weight Loss')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this template is for')),
                ('category', models.CharField(choices=[('health', 'Health & Wellness'), ('business', 'Business & Career'), ('personal', 'Personal Development'), ('finance', 'Finance & Trading'), ('academic', 'Academic'), ('other', 'Other')], default='other', help_text='Category for grouping templates', max_length=20)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-brain', 'fa-chart-line')", max_length=50)),
                ('color', models.CharField(default='#10b981', help_text='Hex color for template (e.g., #10b981)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for selection')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('template_fields', models.JSONField(blank=True, default=list, help_text='Optional: Custom fields structure for this template type')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Template',
                'verbose_name_plural': 'Project Templates',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at', 'title'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Project template (e.g., Mindset, Trading, Weight Loss)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='dashboard_user.projecttemplate'),
        ),
    ]
