# Generated by Django 5.2.3 on 2026-01-18 12:00

from django.db import migrations
import django.utils.timezone


def create_initial_templates(apps, schema_editor):
    """Create initial project templates"""
    ProjectTemplate = apps.get_model('dashboard_user', 'ProjectTemplate')
    
    templates = [
        {
            'name': 'Mindset',
            'description': 'Develop a positive mindset and overcome limiting beliefs',
            'category': 'personal',
            'icon': 'fa-brain',
            'color': '#8b5cf6',
            'order': 1,
        },
        {
            'name': 'Trading',
            'description': 'Learn trading strategies and market analysis',
            'category': 'finance',
            'icon': 'fa-chart-line',
            'color': '#10b981',
            'order': 2,
        },
        {
            'name': 'Weight Loss',
            'description': 'Create a sustainable weight loss plan and track progress',
            'category': 'health',
            'icon': 'fa-weight',
            'color': '#f59e0b',
            'order': 3,
        },
        {
            'name': 'Business Plan',
            'description': 'Develop a comprehensive business plan and strategy',
            'category': 'business',
            'icon': 'fa-briefcase',
            'color': '#3b82f6',
            'order': 4,
        },
    ]
    
    for template_data in templates:
        ProjectTemplate.objects.get_or_create(
            name=template_data['name'],
            defaults={
                'description': template_data['description'],
                'category': template_data['category'],
                'icon': template_data['icon'],
                'color': template_data['color'],
                'order': template_data['order'],
                'is_active': True,
                'created_at': django.utils.timezone.now(),
            }
        )


def reverse_initial_templates(apps, schema_editor):
    """Remove initial templates"""
    ProjectTemplate = apps.get_model('dashboard_user', 'ProjectTemplate')
    template_names = ['Mindset', 'Trading', 'Weight Loss', 'Business Plan']
    ProjectTemplate.objects.filter(name__in=template_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0002_projecttemplate_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_templates, reverse_initial_templates),
    ]
