# Generated by Django 5.2.3 on 2026-01-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0003_populate_initial_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Project description'),
        ),
    ]
