# Generated by Django 5.2.3 on 2026-01-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0004_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='image',
            field=models.ImageField(blank=True, help_text='Template image/icon', null=True, upload_to='project_templates/'),
        ),
    ]
