# Generated by Django 5.2.3 on 2026-01-19 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_mentorclientrelationship_review_provided_and_more'),
        ('dashboard_user', '0005_projecttemplate_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('module_type', models.CharField(choices=[('financial_planning', 'Financial Planning'), ('real_world_validation', 'Real World Validation'), ('progress_tracking', 'Progress Tracking'), ('milestone_checkpoints', 'Milestone Checkpoints'), ('resource_management', 'Resource Management'), ('stakeholder_feedback', 'Stakeholder Feedback'), ('risk_assessment', 'Risk Assessment'), ('timeline_management', 'Timeline Management'), ('habit_tracking', 'Habit Tracking'), ('identity_mindset', 'Identity/Mindset Tracking'), ('career_transition', 'Career Transition'), ('health_metrics', 'Health Metrics')], max_length=50)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#10b981', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('config_schema', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Project Module',
                'verbose_name_plural': 'Project Modules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='assignment_status',
            field=models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Assigned'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='assignment_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='current_status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='questionnaire_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='questionnaire_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='has_default_questions',
            field=models.BooleanField(default=True, help_text='Whether to use default questions for blank projects using this template'),
        ),
        migrations.CreateModel(
            name='ProjectQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multiple Select')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/multiselect questions')),
                ('help_text', models.TextField(blank=True)),
                ('template', models.ForeignKey(blank=True, help_text='Template this question belongs to (null for default questions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard_user.projecttemplate')),
            ],
            options={
                'verbose_name': 'Project Questionnaire',
                'verbose_name_plural': 'Project Questionnaires',
                'ordering': ['order'],
                'unique_together': {('template', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_from_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='blocks', to='dashboard_user.projectstage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='dashboard_user.project')),
            ],
            options={
                'verbose_name': 'Project Stage',
                'verbose_name_plural': 'Project Stages',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStageNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('author_role', models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('client', 'Client')], max_length=20)),
                ('is_author_deleted', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='dashboard_user.projectstage')),
            ],
            options={
                'verbose_name': 'Project Stage Note',
                'verbose_name_plural': 'Project Stage Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStageNoteAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_stages/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard_user.projectstagenote')),
            ],
            options={
                'verbose_name': 'Project Stage Note Attachment',
                'verbose_name_plural': 'Project Stage Note Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStageNoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('author_role', models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('client', 'Client')], max_length=20)),
                ('is_author_deleted', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard_user.projectstagenote')),
            ],
            options={
                'verbose_name': 'Project Stage Note Comment',
                'verbose_name_plural': 'Project Stage Note Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('default_target_date_offset', models.IntegerField(blank=True, help_text='Days from project start date for default target date', null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_templates', to='dashboard_user.projecttemplate')),
            ],
            options={
                'verbose_name': 'Project Stage Template',
                'verbose_name_plural': 'Project Stage Templates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('order', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('author_email', models.EmailField(blank=True, max_length=254)),
                ('author_role', models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('client', 'Client')], max_length=20)),
                ('is_author_deleted', models.BooleanField(default=False)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Client this task is assigned to (for future multi-client projects)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='accounts.userprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ManyToManyField(blank=True, related_name='blocked_by', to='dashboard_user.task')),
                ('mentor_backlog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_backlog_tasks', to='accounts.mentorprofile')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_tasks', to='dashboard_user.projectstage')),
                ('user_active_backlog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_backlog_tasks', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectModuleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('module_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_user.projectmodule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_instances', to='dashboard_user.project')),
            ],
            options={
                'verbose_name': 'Project Module Instance',
                'verbose_name_plural': 'Project Module Instances',
                'ordering': ['order'],
                'unique_together': {('project', 'module')},
            },
        ),
        migrations.CreateModel(
            name='ProjectQuestionnaireAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_answers', to='dashboard_user.project')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_user.projectquestionnaire')),
            ],
            options={
                'verbose_name': 'Project Questionnaire Answer',
                'verbose_name_plural': 'Project Questionnaire Answers',
                'ordering': ['question__order'],
                'unique_together': {('project', 'question')},
            },
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['project', 'order'], name='dashboard_u_project_ecbca5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstagetemplate',
            unique_together={('template', 'order')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['stage', 'order'], name='dashboard_u_stage_i_0e80b4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user_active_backlog', 'order'], name='dashboard_u_user_ac_5ce943_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['mentor_backlog', 'order'], name='dashboard_u_mentor__99f4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status', 'priority'], name='dashboard_u_status_455a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned', 'assigned_to'], name='dashboard_u_assigne_86455e_idx'),
        ),
    ]
