# Generated by Django 5.2.3 on 2026-01-19 02:01

from django.db import migrations


def create_default_questions(apps, schema_editor):
    """Create default questions for blank projects"""
    ProjectQuestionnaire = apps.get_model('dashboard_user', 'ProjectQuestionnaire')
    
    default_questions = [
        {
            'question_text': 'What is your current situation or starting point?',
            'question_type': 'textarea',
            'is_required': True,
            'order': 1,
            'help_text': 'Describe where you are right now in relation to your goal.',
        },
        {
            'question_text': 'What is your main goal or desired outcome?',
            'question_type': 'textarea',
            'is_required': True,
            'order': 2,
            'help_text': 'Be as specific as possible about what you want to achieve.',
        },
        {
            'question_text': 'What is your target completion date?',
            'question_type': 'date',
            'is_required': False,
            'order': 3,
            'help_text': 'When would you like to achieve this goal?',
        },
        {
            'question_text': 'What challenges or obstacles do you anticipate?',
            'question_type': 'textarea',
            'is_required': False,
            'order': 4,
            'help_text': 'List any potential difficulties you might face.',
        },
        {
            'question_text': 'What resources or support do you have available?',
            'question_type': 'textarea',
            'is_required': False,
            'order': 5,
            'help_text': 'Consider time, money, people, skills, or other resources.',
        },
        {
            'question_text': 'What steps have you already taken towards this goal?',
            'question_type': 'textarea',
            'is_required': False,
            'order': 6,
            'help_text': 'Describe any previous attempts or progress made.',
        },
        {
            'question_text': 'How will you measure success?',
            'question_type': 'textarea',
            'is_required': False,
            'order': 7,
            'help_text': 'What metrics or indicators will show you\'ve achieved your goal?',
        },
    ]
    
    for question_data in default_questions:
        ProjectQuestionnaire.objects.get_or_create(
            template=None,  # Default questions have no template
            question_text=question_data['question_text'],
            defaults={
                'question_type': question_data['question_type'],
                'is_required': question_data['is_required'],
                'order': question_data['order'],
                'help_text': question_data['help_text'],
                'options': [],
            }
        )


def reverse_default_questions(apps, schema_editor):
    """Remove default questions"""
    ProjectQuestionnaire = apps.get_model('dashboard_user', 'ProjectQuestionnaire')
    ProjectQuestionnaire.objects.filter(template__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0006_projectmodule_project_assignment_status_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_questions, reverse_default_questions),
    ]
