# Generated by Django 5.2.3 on 2026-01-19 02:15

from django.db import migrations


def create_initial_modules(apps, schema_editor):
    """Create initial project modules"""
    ProjectModule = apps.get_model('dashboard_user', 'ProjectModule')
    
    modules = [
        {
            'name': 'Financial Planning',
            'module_type': 'financial_planning',
            'description': 'Track expenses, budget, and financial projections for your project',
            'icon': 'fa-dollar-sign',
            'color': '#10b981',
            'order': 1,
        },
        {
            'name': 'Real World Validation',
            'module_type': 'real_world_validation',
            'description': 'Gather feedback, test assumptions, and validate your ideas with real users',
            'icon': 'fa-check-circle',
            'color': '#3b82f6',
            'order': 2,
        },
        {
            'name': 'Progress Tracking',
            'module_type': 'progress_tracking',
            'description': 'Monitor your progress with metrics, milestones, and visual indicators',
            'icon': 'fa-chart-line',
            'color': '#8b5cf6',
            'order': 3,
        },
        {
            'name': 'Milestone Checkpoints',
            'module_type': 'milestone_checkpoints',
            'description': 'Set and track key milestones to measure your progress',
            'icon': 'fa-flag-checkered',
            'color': '#f59e0b',
            'order': 4,
        },
        {
            'name': 'Resource Management',
            'module_type': 'resource_management',
            'description': 'Manage and allocate resources needed for your project',
            'icon': 'fa-boxes',
            'color': '#ef4444',
            'order': 5,
        },
        {
            'name': 'Stakeholder Feedback',
            'module_type': 'stakeholder_feedback',
            'description': 'Collect and manage feedback from stakeholders and team members',
            'icon': 'fa-comments',
            'color': '#06b6d4',
            'order': 6,
        },
        {
            'name': 'Risk Assessment',
            'module_type': 'risk_assessment',
            'description': 'Identify, assess, and manage potential risks to your project',
            'icon': 'fa-exclamation-triangle',
            'color': '#f97316',
            'order': 7,
        },
        {
            'name': 'Timeline Management',
            'module_type': 'timeline_management',
            'description': 'Plan and track project timelines and deadlines',
            'icon': 'fa-calendar-alt',
            'color': '#6366f1',
            'order': 8,
        },
        {
            'name': 'Habit Tracking',
            'module_type': 'habit_tracking',
            'description': 'Build and track habits that support your project goals',
            'icon': 'fa-redo',
            'color': '#14b8a6',
            'order': 9,
        },
        {
            'name': 'Identity/Mindset Tracking',
            'module_type': 'identity_mindset',
            'description': 'Track mindset shifts and identity changes related to your goals',
            'icon': 'fa-brain',
            'color': '#a855f7',
            'order': 10,
        },
        {
            'name': 'Career Transition',
            'module_type': 'career_transition',
            'description': 'Tools and resources for navigating career changes',
            'icon': 'fa-briefcase',
            'color': '#ec4899',
            'order': 11,
        },
        {
            'name': 'Health Metrics',
            'module_type': 'health_metrics',
            'description': 'Track health-related metrics and wellness indicators',
            'icon': 'fa-heartbeat',
            'color': '#f43f5e',
            'order': 12,
        },
    ]
    
    for module_data in modules:
        ProjectModule.objects.get_or_create(
            name=module_data['name'],
            defaults={
                'module_type': module_data['module_type'],
                'description': module_data['description'],
                'icon': module_data['icon'],
                'color': module_data['color'],
                'order': module_data['order'],
                'is_active': True,
                'config_schema': {},
            }
        )


def reverse_initial_modules(apps, schema_editor):
    """Remove initial modules"""
    ProjectModule = apps.get_model('dashboard_user', 'ProjectModule')
    ProjectModule.objects.filter(
        module_type__in=[
            'financial_planning', 'real_world_validation', 'progress_tracking',
            'milestone_checkpoints', 'resource_management', 'stakeholder_feedback',
            'risk_assessment', 'timeline_management', 'habit_tracking',
            'identity_mindset', 'career_transition', 'health_metrics'
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0007_populate_default_questions'),
    ]

    operations = [
        migrations.RunPython(create_initial_modules, reverse_initial_modules),
    ]
