# Generated by Django 5.2.3 on 2026-01-19 02:30

from django.db import migrations


def create_stage_templates(apps, schema_editor):
    """Create stage templates for existing project templates"""
    ProjectTemplate = apps.get_model('dashboard_user', 'ProjectTemplate')
    ProjectStageTemplate = apps.get_model('dashboard_user', 'ProjectStageTemplate')
    
    # Get existing templates
    templates = ProjectTemplate.objects.all()
    
    # Stage templates for each template type
    stage_templates_data = {
        'Mindset': [
            {
                'title': 'Self-Awareness Assessment',
                'description': 'Identify current mindset patterns, limiting beliefs, and areas for growth',
                'order': 1,
                'default_target_date_offset': 7,
            },
            {
                'title': 'Goal Setting & Vision',
                'description': 'Define clear goals and create a vision for your desired mindset',
                'order': 2,
                'default_target_date_offset': 14,
            },
            {
                'title': 'Belief System Transformation',
                'description': 'Challenge and reframe limiting beliefs with empowering alternatives',
                'order': 3,
                'default_target_date_offset': 30,
            },
            {
                'title': 'Daily Practice Implementation',
                'description': 'Establish daily routines and practices to reinforce new mindset',
                'order': 4,
                'default_target_date_offset': 45,
            },
            {
                'title': 'Progress Review & Adjustment',
                'description': 'Review progress, celebrate wins, and adjust strategies as needed',
                'order': 5,
                'default_target_date_offset': 60,
            },
        ],
        'Trading': [
            {
                'title': 'Market Fundamentals',
                'description': 'Learn basic market concepts, terminology, and trading principles',
                'order': 1,
                'default_target_date_offset': 7,
            },
            {
                'title': 'Strategy Development',
                'description': 'Develop and test trading strategies based on your risk tolerance',
                'order': 2,
                'default_target_date_offset': 21,
            },
            {
                'title': 'Risk Management Setup',
                'description': 'Establish risk management rules and position sizing strategies',
                'order': 3,
                'default_target_date_offset': 28,
            },
            {
                'title': 'Paper Trading Practice',
                'description': 'Practice trading with virtual money to build confidence',
                'order': 4,
                'default_target_date_offset': 45,
            },
            {
                'title': 'Live Trading & Review',
                'description': 'Begin live trading with small positions and regular review',
                'order': 5,
                'default_target_date_offset': 60,
            },
        ],
        'Weight Loss': [
            {
                'title': 'Initial Assessment',
                'description': 'Assess current weight, body composition, and health metrics',
                'order': 1,
                'default_target_date_offset': 0,
            },
            {
                'title': 'Nutrition Plan Development',
                'description': 'Create a sustainable nutrition plan tailored to your goals',
                'order': 2,
                'default_target_date_offset': 7,
            },
            {
                'title': 'Exercise Routine Setup',
                'description': 'Design an exercise routine that fits your lifestyle',
                'order': 3,
                'default_target_date_offset': 14,
            },
            {
                'title': 'Habit Formation',
                'description': 'Build consistent habits around nutrition and exercise',
                'order': 4,
                'default_target_date_offset': 30,
            },
            {
                'title': 'Progress Tracking & Adjustment',
                'description': 'Monitor progress and adjust plan based on results',
                'order': 5,
                'default_target_date_offset': 60,
            },
        ],
        'Business Plan': [
            {
                'title': 'Market Research',
                'description': 'Research target market, competition, and industry trends',
                'order': 1,
                'default_target_date_offset': 14,
            },
            {
                'title': 'Business Model Development',
                'description': 'Define your business model, value proposition, and revenue streams',
                'order': 2,
                'default_target_date_offset': 28,
            },
            {
                'title': 'Financial Planning',
                'description': 'Create financial projections, budget, and funding strategy',
                'order': 3,
                'default_target_date_offset': 42,
            },
            {
                'title': 'Marketing Strategy',
                'description': 'Develop marketing plan and customer acquisition strategy',
                'order': 4,
                'default_target_date_offset': 56,
            },
            {
                'title': 'Implementation Plan',
                'description': 'Create detailed action plan with milestones and timelines',
                'order': 5,
                'default_target_date_offset': 70,
            },
        ],
    }
    
    # Create stage templates for each template
    for template in templates:
        if template.name in stage_templates_data:
            stages = stage_templates_data[template.name]
            for stage_data in stages:
                ProjectStageTemplate.objects.get_or_create(
                    template=template,
                    title=stage_data['title'],
                    defaults={
                        'description': stage_data['description'],
                        'order': stage_data['order'],
                        'default_target_date_offset': stage_data.get('default_target_date_offset'),
                    }
                )


def reverse_stage_templates(apps, schema_editor):
    """Remove stage templates"""
    ProjectStageTemplate = apps.get_model('dashboard_user', 'ProjectStageTemplate')
    ProjectStageTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0008_populate_project_modules'),
    ]

    operations = [
        migrations.RunPython(create_stage_templates, reverse_stage_templates),
    ]
