# Generated by Django 5.2.3 on 2026-01-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0009_populate_stage_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='is_ai_generated',
            field=models.BooleanField(default=False, help_text='True if stage was generated by AI'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='is_pending_confirmation',
            field=models.BooleanField(default=False, help_text='True if AI-generated stage is pending confirmation'),
        ),
    ]
