# Generated by Django 5.2.8 on 2026-01-19 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_mentorclientrelationship_review_provided_and_more'),
        ('dashboard_user', '0010_add_stage_ai_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttemplate',
            options={'ordering': ['-is_custom', 'order', 'name'], 'verbose_name': 'Project Template', 'verbose_name_plural': 'Project Templates'},
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='author',
            field=models.ForeignKey(blank=True, help_text='The mentor who created this template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_templates', to='accounts.mentorprofile'),
        ),
        migrations.AddField(
            model_name='projecttemplate',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='True if created by a mentor'),
        ),
    ]
