# Generated by Django 5.2.3 on 2026-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0011_alter_projecttemplate_options_projecttemplate_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date for this stage', null=True),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date for this stage', null=True),
        ),
    ]
