# Generated by Django 5.2.3 on 2026-01-20 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0012_add_stage_start_end_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='True if stage is disabled'),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='progress_status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='created', help_text='Current progress status of the stage', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['progress_status'], name='dashboard_u_progres_7f4034_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstage',
            index=models.Index(fields=['is_disabled'], name='dashboard_u_is_disa_d95a81_idx'),
        ),
    ]
