# Generated by Django 5.2.3 on 2026-01-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0013_add_stage_progress_status'),
    ]

    operations = [
        # Delete old models first
        migrations.DeleteModel(
            name='ProjectQuestionnaireAnswer',
        ),
        migrations.DeleteModel(
            name='ProjectQuestionnaire',
        ),
        # Remove fields from ProjectTemplate
        migrations.RemoveField(
            model_name='projecttemplate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projecttemplate',
            name='has_default_questions',
        ),
        # Create new models
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Onboarding Questionnaire', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.OneToOneField(help_text='The questionnaire for this template', on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='dashboard_user.projecttemplate')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multiselect', 'Multiple Select')], default='text', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('options', models.JSONField(blank=True, default=list, help_text='Options for select/multiselect questions')),
                ('help_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(help_text='The questionnaire this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard_user.questionnaire')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['order'],
                'unique_together': {('questionnaire', 'order')},
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=dict, help_text='JSON object mapping question IDs to answers: {question_id: answer_text}')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='The project this response belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to='dashboard_user.project')),
                ('questionnaire', models.ForeignKey(help_text='The questionnaire that was answered', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dashboard_user.questionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire Response',
                'verbose_name_plural': 'Questionnaire Responses',
                'unique_together': {('project', 'questionnaire')},
            },
        ),
    ]
