# Generated by Django 5.2.3 on 2026-01-22 22:06

from django.db import migrations


def create_questionnaires_for_templates(apps, schema_editor):
    """Create questionnaires for all existing templates"""
    ProjectTemplate = apps.get_model('dashboard_user', 'ProjectTemplate')
    Questionnaire = apps.get_model('dashboard_user', 'Questionnaire')
    
    for template in ProjectTemplate.objects.all():
        Questionnaire.objects.get_or_create(template=template)


def reverse_migration(apps, schema_editor):
    """Reverse migration - delete all questionnaires"""
    Questionnaire = apps.get_model('dashboard_user', 'Questionnaire')
    Questionnaire.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0014_remove_projectquestionnaireanswer_question_and_more'),
    ]

    operations = [
        migrations.RunPython(create_questionnaires_for_templates, reverse_migration),
    ]
