# Generated by Django 5.2.3 on 2026-01-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0015_create_questionnaires_for_existing_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this task is linked to (optional, for tasks in mentor backlog)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_tasks', to='dashboard_user.project'),
        ),
    ]
