# Generated by Django 5.2.3 on 2026-01-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0016_task_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectStageTemplate',
        ),
    ]
