# Generated by Django 5.2.3 on 2026-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0017_remove_project_stage_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='preselected_modules',
            field=models.ManyToManyField(blank=True, help_text='Modules that should be automatically selected when using this template', related_name='templates', to='dashboard_user.projectmodule'),
        ),
    ]
