# Generated by Django 5.2.3 on 2026-01-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0018_add_preselected_modules_to_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_target_date',
            field=models.BooleanField(default=False, help_text="If True, this date answer will be used as the project's target completion date. Only one date question per questionnaire can be marked as target date."),
        ),
    ]
