# Generated by Django 5.2.3 on 2026-01-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0019_add_is_target_date_to_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_target_date',
        ),
    ]
