# Generated by Django 5.2.3 on 2026-01-26 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_mentorclientrelationship_review_provided_and_more'),
        ('dashboard_user', '0020_remove_is_target_date_from_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_target_date',
            field=models.BooleanField(default=False, help_text="If True, this date answer will be used as the project's target completion date. Only one date question per questionnaire can be marked as target date."),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when task was marked as completed', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='moved_to_active_backlog_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when task was moved to user's active backlog", null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_by_mentor',
            field=models.ForeignKey(blank=True, help_text='Mentor who reviewed this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to='accounts.mentorprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewed_by_mentor_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when task was reviewed by mentor', null=True),
        ),
    ]
