# Generated by Django 5.2.3 on 2026-01-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0021_add_task_lifecycle_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='created', max_length=20),
        ),
    ]
