# Generated by Django 5.2.3 on 2026-01-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0022_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp when task status became 'active' (when created in active backlog or activated from stage)", null=True),
        ),
    ]
