# Generated by Django 5.2.3 on 2026-02-06 13:37

from django.db import migrations, models


def migrate_task_statuses_forward(apps, schema_editor):
    """Convert old status values to new ones"""
    Task = apps.get_model('dashboard_user', 'Task')
    
    # Map old statuses to new statuses
    status_mapping = {
        'todo': 'pending',
        'created': 'pending',
        'cancelled': 'archived',
        # Keep these as-is
        'active': 'active',
        'in_progress': 'in_progress',
        'review': 'review',
        'completed': 'completed',
        'reviewed': 'review',  # Map reviewed to review
    }
    
    # Update all tasks
    for task in Task.objects.all():
        old_status = task.status
        if old_status in status_mapping:
            task.status = status_mapping[old_status]
            task.save(update_fields=['status'])


def migrate_task_statuses_backward(apps, schema_editor):
    """Revert status values back to old ones"""
    Task = apps.get_model('dashboard_user', 'Task')
    
    # Reverse mapping
    reverse_mapping = {
        'pending': 'todo',
        'archived': 'cancelled',
        # Keep these as-is
        'active': 'active',
        'in_progress': 'in_progress',
        'review': 'review',
        'completed': 'completed',
    }
    
    # Update all tasks
    for task in Task.objects.all():
        new_status = task.status
        if new_status in reverse_mapping:
            task.status = reverse_mapping[new_status]
            task.save(update_fields=['status'])


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_user', '0024_add_project_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Not Activated'), ('active', 'Activated'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
        migrations.RunPython(migrate_task_statuses_forward, migrate_task_statuses_backward),
    ]
