# Generated by Django 5.2.3 on 2025-12-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_custom', models.BooleanField(default=False, help_text='True if created by a mentor, False if predefined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mentor Type',
                'verbose_name_plural': 'Mentor Types',
                'ordering': ['-is_custom', 'name'],
            },
        ),
    ]
