# Generated by Django 5.2.3 on 2025-12-02 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mentor', '0003_populate_mentor_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorType',
        ),
    ]
