# Generated by Django 5.2.3 on 2025-12-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mentor', '0004_delete_mentortype'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='credential',
            name='description',
            field=models.TextField(blank=True, max_length=450),
        ),
    ]
