# Generated by Django 5.2.3 on 2025-12-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_mentorprofile_first_session_free'),
        ('dashboard_mentor', '0006_rename_credential_to_qualification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['title'], 'verbose_name': 'Qualification', 'verbose_name_plural': 'Qualifications'},
        ),
        migrations.CreateModel(
            name='MentorProfileQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('mentor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.mentorprofile')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_mentor.qualification')),
            ],
            options={
                'ordering': ['order', 'qualification__title'],
                'unique_together': {('mentor_profile', 'qualification')},
            },
        ),
    ]
