# Generated by Django 5.2.3 on 2025-12-02 15:49

from django.db import migrations


def migrate_qualifications_to_through(apps, schema_editor):
    """Migrate existing qualifications to through model with order"""
    MentorProfile = apps.get_model('accounts', 'MentorProfile')
    MentorProfileQualification = apps.get_model('dashboard_mentor', 'MentorProfileQualification')
    
    for profile in MentorProfile.objects.all():
        # Get all qualifications for this profile
        qualifications = list(profile.qualifications.all())
        # Create through model instances with order
        for order, qual in enumerate(qualifications):
            MentorProfileQualification.objects.get_or_create(
                mentor_profile=profile,
                qualification=qual,
                defaults={'order': order}
            )


def reverse_migrate_qualifications(apps, schema_editor):
    """Reverse migration - remove through model instances"""
    MentorProfileQualification = apps.get_model('dashboard_mentor', 'MentorProfileQualification')
    MentorProfileQualification.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_mentorprofile_first_session_free'),
        ('dashboard_mentor', '0007_alter_qualification_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_qualifications_to_through, reverse_migrate_qualifications),
    ]
