# Generated by Django 5.2.3 on 2025-12-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mentor', '0008_add_mentor_profile_qualification_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='type',
            field=models.CharField(choices=[('degree', 'Degree'), ('certificate', 'Certificate'), ('license', 'License'), ('diploma', 'Diploma'), ('award', 'Award'), ('training', 'Training'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('publication', 'Publication'), ('research', 'Research'), ('experience', 'Experience'), ('membership', 'Membership'), ('accreditation', 'Accreditation'), ('endorsement', 'Endorsement'), ('other', 'Other')], default='certificate', help_text='Type of qualification to determine the icon displayed', max_length=20),
        ),
    ]
