# Generated by Django 5.2.3 on 2025-12-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mentor', '0010_mentoravailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorAvailability',
        ),
    ]
