# Generated by Django 5.2.3 on 2026-02-07 15:56

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_mentorclientrelationship_review_provided_and_more'),
        ('dashboard_mentor', '0011_remove_mentor_availability_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('button_name', models.CharField(max_length=100)),
                ('image_name', models.CharField(blank=True, help_text='Filename only (e.g. setup-profile.png). Image must exist in static/images/guides/.', max_length=255)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Guide',
                'verbose_name_plural': 'Guides',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GuideStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('button_name', models.CharField(max_length=100)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='dashboard_mentor.guide')),
            ],
            options={
                'verbose_name': 'Guide step',
                'verbose_name_plural': 'Guide steps',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MentorGuideProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dashboard_mentor.guide')),
                ('guide_step', models.ForeignKey(blank=True, help_text='Null = completed main guide; set = completed this subtask', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dashboard_mentor.guidestep')),
                ('mentor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_progress', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Mentor guide progress',
                'verbose_name_plural': 'Mentor guide progress',
                'ordering': ['-completed_at'],
                'constraints': [models.UniqueConstraint(condition=Q(guide_step__isnull=True), fields=('mentor_profile', 'guide'), name='dashboard_mentor_mentorguideprogress_unique_main')],
                'unique_together': {('mentor_profile', 'guide', 'guide_step')},
            },
        ),
    ]
