# Generated by Django 5.2.3 on 2026-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mentor', '0012_add_guide_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='image_name',
        ),
        migrations.AddField(
            model_name='guide',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for this guide (shown on the Next step card).', null=True, upload_to='guides/'),
        ),
    ]
