# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mentor', '0013_guide_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidestep',
            name='url',
            field=models.CharField(
                blank=True,
                help_text='Page to redirect to when the user clicks this subtask (e.g. /dashboard/mentor/profile/).',
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='action_id',
            field=models.CharField(
                blank=True,
                help_text='Optional query param added to url (e.g. ?action_id=...) so the target page knows they came from the guide.',
                max_length=100,
            ),
        ),
    ]
