# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_mentor', '0014_guidestep_url_action_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='ai_coins',
            field=models.PositiveIntegerField(
                default=50,
                help_text='Amount of AI coins awarded for this guide (editable in admin).',
            ),
        ),
        migrations.AddField(
            model_name='guidestep',
            name='ai_coins',
            field=models.PositiveIntegerField(
                default=10,
                help_text='Amount of AI coins awarded for this subtask (editable in admin).',
            ),
        ),
    ]
