from django.urls import path
from . import views

app_name = "dashboard_user"

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('account/', views.account, name='account'),
    path('profile/', views.profile, name='profile'),
    path('settings/', views.settings_view, name='settings'),
    path('support/', views.support_view, name='support'),
    path('my-sessions/', views.my_sessions, name='my_sessions'),
    path('my-sessions/get-sessions/', views.get_sessions_paginated, name='get_sessions_paginated'),
    path('my-sessions/session/<int:session_id>/', views.session_detail, name='session_detail'),
    path('my-sessions/session/<int:session_id>/api/', views.session_detail_api, name='session_detail_api'),
    path('my-sessions/session/<int:session_id>/cancel/', views.cancel_session, name='cancel_session'),
    path('mentors/', views.mentors_list, name='mentors_list'),
    path('mentors/<int:mentor_id>/', views.mentor_detail, name='mentor_detail'),
    path('review/<int:mentor_id>/<str:uid>/<str:token>/', views.write_review, name='write_review'),
    path('reviews/', views.create_edit_review, name='create_review'),
    path('reviews/<int:review_id>/', views.create_edit_review, name='edit_review'),
    path('reviews/<int:review_id>/publish/', views.publish_review, name='publish_review'),
    path('reviews/<int:review_id>/delete/', views.delete_review, name='delete_review'),
    path('session-invitation/<str:token>/', views.session_invitation, name='session_invitation'),
    path('session-management/', views.session_management, name='session_management'),
    path('create-booking-payment-intent/', views.create_booking_payment_intent, name='create_booking_payment_intent'),
    path('create-accept-session-payment-intent/', views.create_accept_session_payment_intent, name='create_accept_session_payment_intent'),
    path('create-wallet-topup-payment-intent/', views.create_wallet_topup_payment_intent, name='create_wallet_topup_payment_intent'),
    path('book-session/', views.book_session, name='book_session'),
    path('booking-modal/<int:mentor_user_id>/', views.booking_modal_partial, name='booking_modal_partial'),
    path('notifications/', views.notification_list, name='notification_list'),
    path('notifications/<int:notification_id>/', views.notification_detail, name='notification_detail'),
    path('notifications/<int:notification_id>/mark-read/', views.notification_mark_read, name='notification_mark_read'),
    path('notifications/mark-all-read/', views.notification_mark_all_read, name='notification_mark_all_read'),
    path('notifications/<int:notification_id>/modal/', views.notification_modal_detail, name='notification_modal_detail'),
    path('tickets/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('projects/', views.projects_list, name='projects_list'),
    path('projects/manage-invitations/', views.manage_project_invitations, name='manage_project_invitations'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/accept/<str:uidb64>/<str:token>/', views.accept_project_assignment_secure, name='accept_project_assignment_secure'),
    path('projects/<int:project_id>/accept/', views.accept_project_assignment, name='accept_project_assignment'),
    path('projects/<int:project_id>/reject/', views.reject_project_assignment, name='reject_project_assignment'),
    path('projects/<int:project_id>/questionnaire/', views.submit_questionnaire, name='submit_questionnaire'),
    path('projects/<int:project_id>/modules/<int:module_id>/', views.module_detail, name='module_detail'),
    path('active-backlog/', views.active_backlog, name='active_backlog'),
    path('active-backlog/tasks/create/', views.create_active_backlog_task, name='create_active_backlog_task'),
    path('active-backlog/tasks/<int:task_id>/edit/', views.edit_active_backlog_task, name='edit_active_backlog_task'),
    path('active-backlog/tasks/<int:task_id>/toggle-complete/', views.toggle_active_backlog_task_complete, name='toggle_active_backlog_task_complete'),
    path('active-backlog/tasks/<int:task_id>/delete/', views.delete_active_backlog_task, name='delete_active_backlog_task'),
    path('active-backlog/tasks/<int:task_id>/deactivate/', views.deactivate_active_backlog_task, name='deactivate_active_backlog_task'),
    path('active-backlog/api/', views.get_user_active_backlog_api, name='get_user_active_backlog_api'),
    path('projects/<int:project_id>/stages/api/', views.get_stages_api, name='get_stages_api'),
    path('projects/<int:project_id>/stages/<int:stage_id>/', views.stage_detail, name='stage_detail'),
]

