# Generated by Django 5.2.3 on 2025-11-30 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='credentials',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'User')], default='user', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MentorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('mentor', 'Mentor')], default='mentor', editable=False, max_length=10)),
                ('time_zone', models.CharField(blank=True, max_length=64, null=True)),
                ('mentor_type', models.CharField(blank=True, choices=[('life_coach', 'Life Coach'), ('career_coach', 'Career Coach'), ('business_coach', 'Business Coach'), ('health_coach', 'Health Coach'), ('other', 'Other')], max_length=50, null=True)),
                ('bio', models.TextField(blank=True)),
                ('quote', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('billing', models.JSONField(blank=True, default=dict)),
                ('subscription', models.JSONField(blank=True, default=dict)),
                ('promotions', models.JSONField(blank=True, default=list)),
                ('reviews', models.JSONField(blank=True, default=list)),
                ('clients', models.ManyToManyField(blank=True, related_name='mentor_clients', to='accounts.userprofile')),
                ('credentials', models.ManyToManyField(blank=True, related_name='mentors', to='accounts.credential')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Profile',
                'verbose_name_plural': 'Mentor Profiles',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.mentorprofile'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('personal', 'Personal'), ('professional', 'Professional'), ('academic', 'Academic')], default='personal', max_length=20)),
                ('supervised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.project'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('workshop', 'Workshop')], default='individual', max_length=20)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='accounts.session'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='accounts.tag'),
        ),
    ]
