# Generated by Django 5.2.3 on 2025-11-30 15:01

from django.db import migrations


def ensure_user_profiles(apps, schema_editor):
    """Ensure all users have UserProfile"""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    for user in CustomUser.objects.all():
        # Check if user has UserProfile (after migration 0004, it's user_profile)
        try:
            profile = user.user_profile
        except UserProfile.DoesNotExist:
            # Create UserProfile if it doesn't exist
            UserProfile.objects.create(
                user=user,
                first_name="",
                last_name="",
                role='user'
            )


def reverse_migration(apps, schema_editor):
    """Reverse migration - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_credential_tag_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_user_profiles, reverse_migration),
    ]
