# Generated by Django 5.2.3 on 2025-11-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_migrate_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='accounts.session'),
        ),
    ]
