# Generated by Django 5.2.3 on 2025-11-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_sessions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credential',
            options={'ordering': ['title'], 'verbose_name': 'Credential', 'verbose_name_plural': 'Mentor Profile > Credentials'},
        ),
        migrations.AlterModelOptions(
            name='mentorprofile',
            options={'verbose_name': 'Mentor Profile', 'verbose_name_plural': 'Mentor Profile > Mentor Profiles'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title'], 'verbose_name': 'Project', 'verbose_name_plural': 'User Profile > Projects'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_datetime'], 'verbose_name': 'Session', 'verbose_name_plural': 'User Profile > Sessions'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Mentor Profile > Tags'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile > User Profiles'},
        ),
    ]
