# Generated by Django 5.2.3 on 2025-11-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_credential_options_alter_mentorprofile_options_and_more'),
        ('general', '0001_initial'),
        ('dashboard_mentor', '0001_initial'),
    ]

    operations = [
        # Remove old ManyToManyField first (before deleting models)
        migrations.RemoveField(
            model_name='mentorprofile',
            name='credentials',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='sessions',
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sessions',
        ),
        # Remove fields from models before deleting them
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supervised_by',
        ),
        migrations.RemoveField(
            model_name='session',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='session',
            name='created_by',
        ),
        # Delete old models
        migrations.DeleteModel(
            name='Credential',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        # Add new ManyToManyField with new targets
        migrations.AddField(
            model_name='mentorprofile',
            name='credentials',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='dashboard_mentor.credential'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='general.session'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mentors', to='dashboard_mentor.tag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='general.session'),
        ),
    ]
