# Generated by Django 5.2.3 on 2025-12-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_credential_remove_project_project_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='manuals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manuals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
