# Generated by Django 5.2.3 on 2025-12-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mentorprofile_manuals_userprofile_manuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='mentor_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='mentorprofile',
            name='tags',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
