# Generated by Django 5.2.3 on 2025-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_mentorprofile_mentor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='first_session_free',
            field=models.CharField(blank=True, choices=[], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='instagram_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='linkedin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='price_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
