# Generated by Django 5.2.3 on 2025-12-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_credentials_to_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='first_session_free',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('15', '15 minutes'), ('20', '20 minutes'), ('25', '25 minutes'), ('30', '30 minutes'), ('35', '35 minutes'), ('40', '40 minutes'), ('45', '45 minutes'), ('50', '50 minutes'), ('55', '55 minutes'), ('60', '60 minutes')], max_length=10, null=True),
        ),
    ]
