# Generated by Django 5.2.3 on 2025-12-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_mentorprofile_first_session_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='session_length',
            field=models.PositiveIntegerField(blank=True, help_text='Session length in minutes', null=True),
        ),
    ]
