# Generated by Django 5.2.3 on 2025-12-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_mentorprofile_session_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='first_session_length',
            field=models.PositiveIntegerField(blank=True, help_text='First session length in minutes (only used if first_session_free is True)', null=True),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='first_session_free',
            field=models.BooleanField(default=False, help_text='Offer first session for free'),
        ),
    ]
