# Generated by Django 5.2.3 on 2025-12-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_mentorprofile_first_session_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='session_length',
            field=models.PositiveIntegerField(blank=True, default=60, help_text='Session length in minutes', null=True),
        ),
    ]
