# Generated by Django 5.2.3 on 2025-12-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_mentorprofile_session_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='first_time_login',
            field=models.BooleanField(default=True, help_text="True if user hasn't completed first login timezone setup"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_time_login',
            field=models.BooleanField(default=True, help_text="True if user hasn't completed first login timezone setup"),
        ),
    ]
