# Generated by Django 5.2.3 on 2025-12-03 17:26

from django.db import migrations, models


def migrate_timezone_data(apps, schema_editor):
    """Migrate existing time_zone values to selected_timezone and detected_timezone"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    MentorProfile = apps.get_model('accounts', 'MentorProfile')
    
    # Migrate UserProfile
    for profile in UserProfile.objects.all():
        if profile.time_zone:
            profile.selected_timezone = profile.time_zone
            profile.detected_timezone = profile.time_zone
            profile.save()
    
    # Migrate MentorProfile
    for profile in MentorProfile.objects.all():
        if profile.time_zone:
            profile.selected_timezone = profile.time_zone
            profile.detected_timezone = profile.time_zone
            profile.save()


def reverse_migration(apps, schema_editor):
    """Reverse migration - copy selected_timezone back to time_zone"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    MentorProfile = apps.get_model('accounts', 'MentorProfile')
    
    # Migrate UserProfile
    for profile in UserProfile.objects.all():
        if profile.selected_timezone:
            profile.time_zone = profile.selected_timezone
            profile.save()
    
    # Migrate MentorProfile
    for profile in MentorProfile.objects.all():
        if profile.selected_timezone:
            profile.time_zone = profile.selected_timezone
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_add_first_time_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='first_time_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_time_login',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='confirmed_timezone_mismatch',
            field=models.BooleanField(default=False, help_text='True if user confirmed they want to keep a different timezone than detected'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='detected_timezone',
            field=models.CharField(blank=True, help_text='Browser-detected timezone, updated on each page load', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='selected_timezone',
            field=models.CharField(blank=True, help_text="User's selected/preferred timezone", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='confirmed_timezone_mismatch',
            field=models.BooleanField(default=False, help_text='True if user confirmed they want to keep a different timezone than detected'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='detected_timezone',
            field=models.CharField(blank=True, help_text='Browser-detected timezone, updated on each page load', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_timezone',
            field=models.CharField(blank=True, help_text="User's selected/preferred timezone", max_length=64, null=True),
        ),
        migrations.RunPython(
            migrate_timezone_data,
            reverse_migration,
        ),
    ]
