# Generated by Django 5.2.3 on 2025-12-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_timezone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='first_time_login',
            field=models.BooleanField(default=True, help_text="True if user hasn't completed first login timezone setup"),
        ),
    ]
