# Generated by Django 5.2.3 on 2025-12-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_first_time_login_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='first_time_login',
        ),
    ]
