# Generated by Django 5.2.3 on 2025-12-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_change_nationality_to_array'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='nationality',
            field=models.JSONField(blank=True, default=list, help_text='Array of nationality IDs from predefined list'),
        ),
    ]
