# Generated by Django 5.2.3 on 2025-12-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_change_nationality_to_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text="Designates whether this user's email has been verified."),
        ),
    ]
