# Generated by Django 5.2.3 on 2025-12-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='nationality',
        ),
    ]
