# Generated by Django 5.2.3 on 2025-12-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_nationality_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover/banner image for profile', null=True, upload_to='profiles/covers/'),
        ),
    ]
