# Generated by Django 5.2.3 on 2025-12-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_mentorprofile_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorClientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_verification', 'Pending Verification'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending_verification', max_length=20)),
                ('invitation_token', models.CharField(blank=True, help_text='Token for invitation completion', max_length=64, null=True, unique=True)),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True, help_text='When the invitation was sent')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the client completed registration', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_relationships', to='accounts.userprofile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_relationships', to='accounts.mentorprofile')),
            ],
            options={
                'verbose_name': 'Mentor-Client Relationship',
                'verbose_name_plural': 'Mentor-Client Relationships',
                'ordering': ['-created_at'],
                'unique_together': {('mentor', 'client')},
            },
        ),
    ]
