# Generated by Django 5.2.3 on 2025-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_mentorclientrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorclientrelationship',
            name='confirmation_token',
            field=models.CharField(blank=True, help_text='Token for existing user confirmation', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorclientrelationship',
            name='invitation_token',
            field=models.CharField(blank=True, help_text='Token for new user invitation completion', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorclientrelationship',
            name='invited_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the invitation/confirmation was sent'),
        ),
        migrations.AlterField(
            model_name='mentorclientrelationship',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('waiting_confirmation', 'Waiting for Confirmation'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending_verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='mentorclientrelationship',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the client completed registration or confirmed', null=True),
        ),
    ]
