# Generated by Django 5.2.3 on 2025-12-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_mentorclientrelationship_confirmation_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorclientrelationship',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='True if the client has confirmed the invitation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_time_login',
            field=models.BooleanField(default=True, help_text="True if user hasn't completed first login timezone setup"),
        ),
        migrations.AlterField(
            model_name='mentorclientrelationship',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('denied', 'Denied')], default='inactive', max_length=20),
        ),
    ]
