# Generated by Django 5.2.3 on 2025-12-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_update_mentor_client_relationship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorclientrelationship',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('active', 'Active'), ('inactive', 'Inactive'), ('denied', 'Denied')], default='inactive', max_length=20),
        ),
    ]
