# Generated by Django 5.2.8 on 2025-12-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_add_confirmed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='qualifications',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='qualifications',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
