# Generated by Django 5.2.3 on 2025-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_mentorprofile_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='availability_slots',
            field=models.JSONField(blank=True, default=list, help_text='List of one-time availability windows'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='recurring_availability_slots',
            field=models.JSONField(blank=True, default=list, help_text='List of recurring weekly/daily rules'),
        ),
    ]
