# Generated by Django 5.2.3 on 2025-12-10 15:59

from django.db import migrations, models


def copy_availability_data(apps, schema_editor):
    """Copy data from old fields to new fields"""
    MentorProfile = apps.get_model('accounts', 'MentorProfile')
    for profile in MentorProfile.objects.all():
        # Copy one-time slots
        if profile.availability_slots:
            profile.one_time_slots = profile.availability_slots
        # Copy recurring slots
        if profile.recurring_availability_slots:
            profile.recurring_slots = profile.recurring_availability_slots
        profile.save()


def reverse_copy_availability_data(apps, schema_editor):
    """Reverse: copy data from new fields back to old fields"""
    MentorProfile = apps.get_model('accounts', 'MentorProfile')
    for profile in MentorProfile.objects.all():
        # Copy one-time slots back
        if profile.one_time_slots:
            profile.availability_slots = profile.one_time_slots
        # Copy recurring slots back
        if profile.recurring_slots:
            profile.recurring_availability_slots = profile.recurring_slots
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_add_availability_json_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='one_time_slots',
            field=models.JSONField(blank=True, default=list, help_text='List of one-time availability windows'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='recurring_slots',
            field=models.JSONField(blank=True, default=list, help_text='List of recurring availability rules'),
        ),
        migrations.RunPython(copy_availability_data, reverse_copy_availability_data),
        migrations.AlterField(
            model_name='mentorprofile',
            name='availability_slots',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use one_time_slots'),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='recurring_availability_slots',
            field=models.JSONField(blank=True, default=list, help_text='DEPRECATED: Use recurring_slots'),
        ),
    ]
