# Generated by Django 5.2.3 on 2025-12-14 18:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_add_type_field_to_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorprofile',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover/banner image for profile', max_length=255, null=True, upload_to=accounts.models.mentor_cover_image_upload_to),
        ),
        migrations.AlterField(
            model_name='mentorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.models.mentor_profile_picture_upload_to),
        ),
    ]
