# Generated by Django 5.2.3 on 2025-12-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_mentorprofile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='collisions',
            field=models.BooleanField(default=False, help_text='True when mentor has unresolved availability collisions (e.g. after increasing session length).'),
        ),
    ]
