# Generated by Django 5.2.8 on 2026-01-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_mentorprofile_collisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='marketing_quiz_url',
            field=models.URLField(blank=True, help_text="URL for mentor's marketing quiz/funnel", null=True),
        ),
    ]
