# Generated by Django 5.2.8 on 2026-01-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_mentorprofile_marketing_quiz_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='intro_video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo URL for intro video', null=True),
        ),
    ]
