# Generated by Django 5.2.8 on 2026-01-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_mentorprofile_intro_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorprofile',
            name='intro_video_url',
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='video_introduction_url',
            field=models.URLField(blank=True, help_text='URL to YouTube/Vimeo introduction video', null=True),
        ),
    ]
