# Generated by Django 5.2.3 on 2026-01-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_remove_mentorprofile_intro_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorclientrelationship',
            name='first_session_scheduled',
            field=models.BooleanField(default=False, help_text='True if the first session has been scheduled (booked) with this mentor'),
        ),
    ]
