# Generated by Django 5.2.3 on 2026-01-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_add_first_session_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorclientrelationship',
            name='first_session_scheduled',
            field=models.BooleanField(blank=True, default=False, help_text='True if the first session has been scheduled (booked) with this mentor'),
        ),
    ]
