# Generated by Django 5.2.3 on 2026-01-15 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_update_first_session_scheduled_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Admin')], default='admin', editable=False, max_length=10)),
                ('detected_timezone', models.CharField(blank=True, help_text='Browser-detected timezone, updated on each page load', max_length=64, null=True)),
                ('selected_timezone', models.CharField(blank=True, help_text="User's selected/preferred timezone", max_length=64, null=True)),
                ('confirmed_timezone_mismatch', models.BooleanField(default=False, help_text='True if user confirmed they want to keep a different timezone than detected')),
                ('time_zone', models.CharField(blank=True, max_length=64, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
            },
        ),
    ]
