# Generated by Django 5.2.3 on 2026-01-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorclientrelationship',
            name='review_provided',
            field=models.BooleanField(default=False, help_text='True if the client has provided a review'),
        ),
        migrations.AddField(
            model_name='mentorclientrelationship',
            name='review_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the mentor last requested a review from this client', null=True),
        ),
    ]
