# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_mentorclientrelationship_review_provided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='ai_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
