# Generated by Django (social fields for UserProfile - client users)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_mentorprofile_ai_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='video_introduction_url',
            field=models.URLField(blank=True, help_text='URL to YouTube/Vimeo or other video', null=True),
        ),
    ]
