# Generated by Django - mentor private notes on relationship

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_userprofile_social_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorclientrelationship',
            name='mentor_notes',
            field=models.TextField(blank=True, help_text='Private notes about this client, visible only to the mentor', null=True),
        ),
    ]
