# Generated by Django 5.2.9 on 2026-02-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_mentorclientrelationship_mentor_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
