# Generated by Django 5.2.3 on 2026-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_add_wallet_balance_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='wallet_balance_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
