# Generated by Django 5.2.3 on 2026-02-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_mentorprofile_wallet_balance_cents'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.CharField(default='FREE', help_text='User subscription tier. FREE means AI tools are not available.', max_length=50),
        ),
    ]
