# Generated by Django 5.2.3 on 2025-11-30 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('session_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('workshop', 'Workshop')], default='individual', max_length=20)),
                ('tasks', models.JSONField(blank=True, default=list)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-start_datetime'],
            },
        ),
    ]

