# Generated by Django 5.2.3 on 2025-12-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('invited', 'Invited'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
