# Generated by Django 5.2.3 on 2025-12-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_session_expires_at_session_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
