# Generated by Django 5.2.3 on 2025-12-17 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_sessioninvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninvitation',
            name='last_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
