# Generated by Django 5.2.3 on 2026-01-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_sessioninvitation_last_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='changes_requested_by',
            field=models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('client', 'Client')], help_text='Indicates who requested the pending changes: mentor or client. NULL means no pending change exists.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='previous_data',
            field=models.JSONField(blank=True, help_text='Full original snapshot of session data before changes. JSON structure mirrors current session fields exactly. Populated while waiting for client confirmation, cleared on confirmation or cancellation.', null=True),
        ),
    ]
