# Generated by Django 5.2.3 on 2026-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_add_session_pending_changes_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='changed_by',
            field=models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('client', 'Client')], help_text="Indicates who made the changes: 'mentor' when mentor saves changes, 'client' for client-initiated changes. Cleared when client confirms or declines.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='original_data',
            field=models.JSONField(blank=True, help_text='Stores the original session data as JSON when mentor saves changes. If empty, add JSON on save. If not empty, rewrite on save. Cleared when client confirms or declines.', null=True),
        ),
    ]
