# Generated by Django 5.2.3 on 2026-01-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_add_original_data_and_changed_by_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='changed_by',
            field=models.CharField(blank=True, choices=[('mentor', 'Mentor'), ('client', 'Client')], help_text="Indicates who initiated the changes: mentor or client. Set to 'mentor' when mentor saves changes, cleared when client confirms or declines.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='original_data',
            field=models.JSONField(blank=True, help_text='Original session data snapshot when mentor saves changes. Stores full session state before changes. Cleared when client confirms or declines.', null=True),
        ),
    ]
