# Generated by Django 5.2.3 on 2026-01-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_add_original_data_and_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('invited', 'Invited'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
    ]
