# Generated by Django 5.2.3 on 2026-01-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_session_client_first_name_session_client_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='first_lesson_user_note',
            field=models.TextField(blank=True, help_text='Note from user when booking their first session', null=True),
        ),
    ]
