# Generated by Django 5.2.3 on 2026-01-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_add_first_lesson_user_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.CharField(choices=[('all', 'All Users'), ('all_users', 'All User Role'), ('all_mentors', 'All Mentor Role'), ('single', 'Single User')], db_index=True, default='all', help_text='Target audience type when notification was created', max_length=20),
        ),
    ]
