# Generated by Django 5.2.3 on 2026-01-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_add_ticket_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attachment (max 5MB)', null=True, upload_to='ticket_comments/'),
        ),
    ]
