# Generated by Django 5.2.3 on 2026-01-16 15:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import general.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_ticketcomment_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('content', models.TextField(help_text='Rich text content of the blog post')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt for preview (optional)', max_length=500)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the blog post (max 5MB)', max_length=255, null=True, upload_to=general.models.blog_cover_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('cover_color', models.CharField(default='#10b981', help_text='Hex color for cover placeholder (e.g., #10b981)', max_length=7)),
                ('categories', models.JSONField(blank=True, default=list, help_text='Array of category IDs from predefined categories')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Draft posts are only visible in management pages, not in public blog', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Publication date (set when status changes to published)', null=True)),
                ('author', models.ForeignKey(help_text='Author of the blog post', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='general_blo_status_88f0ca_idx'), models.Index(fields=['author', '-created_at'], name='general_blo_author__4558ba_idx'), models.Index(fields=['slug'], name='general_blo_slug_cce6ac_idx')],
            },
        ),
    ]
