# Generated by Django 5.2.3 on 2026-01-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0015_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='seo_tags',
            field=models.JSONField(blank=True, default=list, help_text='Array of SEO tags/keywords for meta tags'),
        ),
    ]
