# Generated by Django 5.2.9 on 2026-02-12 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_mentor_nullable_and_wallet_transaction'),
        ('general', '0020_backfill_session_mentors_from_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_session', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='session',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('wallet', 'Wallet'), ('stripe', 'Stripe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
