# Generated by Django 5.2.3 on 2026-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0021_payment_mentor_nullable_and_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='paid_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('invited', 'Invited'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed'), ('payout_available', 'Payout Available'), ('paid_out', 'Paid Out'), ('refunded', 'Refunded')], default='draft', max_length=20),
        ),
    ]
