# Predefined mentor types for autocomplete suggestions
PREDEFINED_MENTOR_TYPES = [
    'Life Coach',
    'Career Coach',
    'Business Coach',
    'Health Coach',
    'Wellness Coach',
    'Fitness Coach',
    'Nutrition Coach',
    'Relationship Coach',
    'Executive Coach',
    'Performance Coach',
    'Leadership Coach',
    'Mindfulness Coach',
    'Spiritual Coach',
    'Financial Coach',
    'Time Management Coach',
    'Personal Development Coach',
    'Confidence Coach',
    'Communication Coach',
    'Public Speaking Coach',
    'Sales Coach',
    'Marketing Coach',
    'Entrepreneurship Coach',
    'Startup Coach',
    'Productivity Coach',
    'Stress Management Coach',
    'Work-Life Balance Coach',
    'Parenting Coach',
    'Dating Coach',
    'Marriage Coach',
    'Grief Coach',
    'Recovery Coach',
    'Addiction Recovery Coach',
    'Weight Loss Coach',
    'Yoga Coach',
    'Meditation Coach',
    'Holistic Health Coach',
    'Mental Health Coach',
    'Therapist',
    'Counselor',
    'Mentor',
    'Advisor',
    'Consultant',
    'Trainer',
    'Instructor',
]

# Predefined tags for filtering mentors
PREDEFINED_TAGS = [
    'Leadership',
    'Communication',
    'Time Management',
    'Goal Setting',
    'Stress Management',
    'Career Development',
    'Business Strategy',
    'Marketing',
    'Sales',
    'Team Building',
    'Conflict Resolution',
    'Public Speaking',
    'Productivity',
    'Work-Life Balance',
    'Confidence Building',
    'Networking',
    'Personal Branding',
    'Financial Planning',
    'Health & Wellness',
    'Nutrition',
    'Fitness',
    'Mental Health',
    'Mindfulness',
    'Meditation',
    'Relationships',
    'Dating',
    'Parenting',
    'Life Transitions',
    'Retirement Planning',
    'Entrepreneurship',
    'Startup',
    'Scaling Business',
    'Digital Marketing',
    'Social Media',
    'Content Creation',
    'Writing',
    'Coaching',
    'Mentoring',
    'Training',
    'Workshop Facilitation',
    'Emotional Intelligence',
    'Self-Awareness',
    'Resilience',
    'Adaptability',
    'Critical Thinking',
    'Problem Solving',
    'Decision Making',
    'Strategic Planning',
    'Project Management',
    'Change Management',
    'Organizational Development',
    'Culture Transformation',
    'Employee Engagement',
    'Talent Development',
    'Succession Planning',
    'Diversity & Inclusion',
    'Women in Leadership',
    'Executive Presence',
    'Influence & Persuasion',
    'Negotiation',
    'Conflict Management',
    'Crisis Management',
    'Risk Management',
    'Innovation',
    'Creativity',
    'Design Thinking',
    'Agile Methodology',
    'Lean Startup',
    'Growth Hacking',
    'SEO',
    'PPC Advertising',
    'Email Marketing',
    'Content Strategy',
    'Brand Development',
    'Customer Experience',
    'User Experience (UX)',
    'Product Development',
    'E-commerce',
    'SaaS',
    'B2B Sales',
    'B2C Sales',
    'Account Management',
    'Client Relations',
    'Stakeholder Management',
    'Presentation Skills',
    'Storytelling',
    'Data Analysis',
    'Business Intelligence',
    'Financial Analysis',
    'Investment Strategy',
    'Retirement Planning',
    'Estate Planning',
    'Tax Planning',
    'Budgeting',
    'Debt Management',
    'Credit Repair',
    'Real Estate',
    'Stock Market',
    'Cryptocurrency',
    'Passive Income',
    'Side Hustle',
    'Freelancing',
    'Remote Work',
    'Time Blocking',
    'Task Management',
    'Goal Achievement',
    'Habit Formation',
    'Self-Discipline',
    'Motivation',
    'Accountability',
    'Mindset Shift',
    'Positive Psychology',
    'Cognitive Behavioral Therapy (CBT)',
    'Dialectical Behavior Therapy (DBT)',
    'Trauma Recovery',
    'PTSD Support',
    'Anxiety Management',
    'Depression Support',
    'ADHD Coaching',
    'Autism Support',
    'Learning Disabilities',
    'Special Needs',
    'Aging & Elder Care',
    'Retirement Transition',
    'Career Change',
    'Job Search',
    'Resume Writing',
    'Interview Preparation',
    'Salary Negotiation',
    'LinkedIn Optimization',
    'Personal Branding Online',
    'Online Presence',
    'Reputation Management',
    'Crisis Communication',
    'Media Training',
    'Podcast Hosting',
    'Video Production',
    'Photography',
    'Graphic Design',
    'Web Design',
    'App Development',
    'Programming',
    'Data Science',
    'Machine Learning',
    'AI Integration',
    'Blockchain',
    'Cybersecurity',
    'Cloud Computing',
    'DevOps',
    'Quality Assurance',
    'Supply Chain',
    'Logistics',
    'Operations',
    'Process Improvement',
    'Six Sigma',
    'Lean Manufacturing',
    'Sustainability',
    'Environmental Management',
    'Corporate Social Responsibility',
    'Nonprofit Management',
    'Fundraising',
    'Grant Writing',
    'Volunteer Management',
    'Event Planning',
    'Wedding Planning',
    'Party Planning',
    'Interior Design',
    'Fashion Styling',
    'Image Consulting',
    'Wardrobe Styling',
    'Beauty & Makeup',
    'Hair Styling',
    'Skincare',
    'Anti-Aging',
    'Holistic Healing',
    'Energy Healing',
    'Reiki',
    'Acupuncture',
    'Herbal Medicine',
    'Ayurveda',
    'Traditional Chinese Medicine',
    'Homeopathy',
    'Naturopathy',
    'Functional Medicine',
    'Integrative Medicine',
    'Pain Management',
    'Chronic Illness',
    'Autoimmune Support',
    'Digestive Health',
    'Hormone Balance',
    'Fertility Support',
    'Pregnancy Support',
    'Postpartum Support',
    'Menopause Support',
    'Sexual Health',
    'Intimacy Coaching',
    'Couples Therapy',
    'Family Therapy',
    'Blended Families',
    'Single Parenting',
    'Teen Support',
    'College Preparation',
    'Study Skills',
    'Test Preparation',
    'Academic Coaching',
    'Homeschooling',
    'Special Education',
    'Gifted & Talented',
    'Arts & Crafts',
    'Music',
    'Singing',
    'Instrument Playing',
    'Dance',
    'Acting',
    'Theater',
    'Writing',
    'Poetry',
    'Journaling',
    'Blogging',
    'Copywriting',
    'Technical Writing',
    'Grant Writing',
    'Screenwriting',
    'Novel Writing',
    'Publishing',
    'Book Marketing',
    'Public Relations',
    'Crisis PR',
    'Investor Relations',
    'Government Relations',
    'Lobbying',
    'Legal',
    'Compliance',
    'Regulatory Affairs',
    'Intellectual Property',
    'Patent Law',
    'Trademark',
    'Copyright',
    'Contract Negotiation',
    'Mergers & Acquisitions',
    'Due Diligence',
    'Business Valuation',
    'Exit Strategy',
    'Succession Planning',
    'Franchising',
    'Licensing',
    'Partnership Development',
    'Joint Ventures',
    'Strategic Alliances',
    'International Business',
    'Export/Import',
    'Cross-Cultural Communication',
    'Cultural Competency',
    'Translation',
    'Interpretation',
    'Localization',
    'Global Expansion',
    'Market Entry',
    'Country-Specific Expertise',
]

# Predefined languages with IDs and flag emojis for filtering
# Format: {'id': 'iso_code', 'name': 'Language Name', 'flag': 'emoji', 'flag_code': 'country_code_for_flag_icon'}
PREDEFINED_LANGUAGES = [
    {'id': 'en', 'name': 'English', 'flag': '🇬🇧', 'flag_code': 'gb'},
    {'id': 'es', 'name': 'Spanish', 'flag': '🇪🇸', 'flag_code': 'es'},
    {'id': 'fr', 'name': 'French', 'flag': '🇫🇷', 'flag_code': 'fr'},
    {'id': 'de', 'name': 'German', 'flag': '🇩🇪', 'flag_code': 'de'},
    {'id': 'it', 'name': 'Italian', 'flag': '🇮🇹', 'flag_code': 'it'},
    {'id': 'pt', 'name': 'Portuguese', 'flag': '🇵🇹', 'flag_code': 'pt'},
    {'id': 'ru', 'name': 'Russian', 'flag': '🇷🇺', 'flag_code': 'ru'},
    {'id': 'zh', 'name': 'Chinese', 'flag': '🇨🇳', 'flag_code': 'cn'},
    {'id': 'ja', 'name': 'Japanese', 'flag': '🇯🇵', 'flag_code': 'jp'},
    {'id': 'ko', 'name': 'Korean', 'flag': '🇰🇷', 'flag_code': 'kr'},
    {'id': 'ar', 'name': 'Arabic', 'flag': '🇸🇦', 'flag_code': 'sa'},
    {'id': 'hi', 'name': 'Hindi', 'flag': '🇮🇳', 'flag_code': 'in'},
    {'id': 'nl', 'name': 'Dutch', 'flag': '🇳🇱', 'flag_code': 'nl'},
    {'id': 'sv', 'name': 'Swedish', 'flag': '🇸🇪', 'flag_code': 'se'},
    {'id': 'pl', 'name': 'Polish', 'flag': '🇵🇱', 'flag_code': 'pl'},
    {'id': 'cs', 'name': 'Czech', 'flag': '🇨🇿', 'flag_code': 'cz'},
    {'id': 'tr', 'name': 'Turkish', 'flag': '🇹🇷', 'flag_code': 'tr'},
    {'id': 'vi', 'name': 'Vietnamese', 'flag': '🇻🇳', 'flag_code': 'vn'},
    {'id': 'th', 'name': 'Thai', 'flag': '🇹🇭', 'flag_code': 'th'},
    {'id': 'he', 'name': 'Hebrew', 'flag': '🇮🇱', 'flag_code': 'il'},
    {'id': 'uk', 'name': 'Ukrainian', 'flag': '🇺🇦', 'flag_code': 'ua'},
    {'id': 'ro', 'name': 'Romanian', 'flag': '🇷🇴', 'flag_code': 'ro'},
    {'id': 'hu', 'name': 'Hungarian', 'flag': '🇭🇺', 'flag_code': 'hu'},
    {'id': 'fi', 'name': 'Finnish', 'flag': '🇫🇮', 'flag_code': 'fi'},
    {'id': 'da', 'name': 'Danish', 'flag': '🇩🇰', 'flag_code': 'dk'},
    {'id': 'no', 'name': 'Norwegian', 'flag': '🇳🇴', 'flag_code': 'no'},
    {'id': 'el', 'name': 'Greek', 'flag': '🇬🇷', 'flag_code': 'gr'},
    {'id': 'bg', 'name': 'Bulgarian', 'flag': '🇧🇬', 'flag_code': 'bg'},
    {'id': 'hr', 'name': 'Croatian', 'flag': '🇭🇷', 'flag_code': 'hr'},
    {'id': 'sk', 'name': 'Slovak', 'flag': '🇸🇰', 'flag_code': 'sk'},
    {'id': 'sl', 'name': 'Slovenian', 'flag': '🇸🇮', 'flag_code': 'si'},
    {'id': 'sr', 'name': 'Serbian', 'flag': '🇷🇸', 'flag_code': 'rs'},
    {'id': 'et', 'name': 'Estonian', 'flag': '🇪🇪', 'flag_code': 'ee'},
    {'id': 'lv', 'name': 'Latvian', 'flag': '🇱🇻', 'flag_code': 'lv'},
    {'id': 'lt', 'name': 'Lithuanian', 'flag': '🇱🇹', 'flag_code': 'lt'},
    {'id': 'id', 'name': 'Indonesian', 'flag': '🇮🇩', 'flag_code': 'id'},
    {'id': 'ms', 'name': 'Malay', 'flag': '🇲🇾', 'flag_code': 'my'},
    {'id': 'tl', 'name': 'Tagalog', 'flag': '🇵🇭', 'flag_code': 'ph'},
    {'id': 'sw', 'name': 'Swahili', 'flag': '🇹🇿', 'flag_code': 'tz'},
    {'id': 'af', 'name': 'Afrikaans', 'flag': '🇿🇦', 'flag_code': 'za'},
    {'id': 'ca', 'name': 'Catalan', 'flag': '🇪🇸', 'flag_code': 'es'},
    {'id': 'eu', 'name': 'Basque', 'flag': '🇪🇸', 'flag_code': 'es'},
    {'id': 'ga', 'name': 'Irish', 'flag': '🇮🇪', 'flag_code': 'ie'},
    {'id': 'mt', 'name': 'Maltese', 'flag': '🇲🇹', 'flag_code': 'mt'},
    {'id': 'is', 'name': 'Icelandic', 'flag': '🇮🇸', 'flag_code': 'is'},
    {'id': 'mk', 'name': 'Macedonian', 'flag': '🇲🇰', 'flag_code': 'mk'},
    {'id': 'sq', 'name': 'Albanian', 'flag': '🇦🇱', 'flag_code': 'al'},
    {'id': 'bs', 'name': 'Bosnian', 'flag': '🇧🇦', 'flag_code': 'ba'},
    {'id': 'bn', 'name': 'Bengali', 'flag': '🇧🇩', 'flag_code': 'bd'},
    {'id': 'ta', 'name': 'Tamil', 'flag': '🇱🇰', 'flag_code': 'lk'},
    {'id': 'te', 'name': 'Telugu', 'flag': '🇮🇳', 'flag_code': 'in'},
    {'id': 'mr', 'name': 'Marathi', 'flag': '🇮🇳', 'flag_code': 'in'},
    {'id': 'gu', 'name': 'Gujarati', 'flag': '🇮🇳', 'flag_code': 'in'},
    {'id': 'kn', 'name': 'Kannada', 'flag': '🇮🇳', 'flag_code': 'in'},
    {'id': 'ml', 'name': 'Malayalam', 'flag': '🇮🇳', 'flag_code': 'in'},
    {'id': 'pa', 'name': 'Punjabi', 'flag': '🇮🇳', 'flag_code': 'in'},
    {'id': 'ur', 'name': 'Urdu', 'flag': '🇵🇰', 'flag_code': 'pk'},
    {'id': 'fa', 'name': 'Persian', 'flag': '🇮🇷', 'flag_code': 'ir'},
    {'id': 'ps', 'name': 'Pashto', 'flag': '🇦🇫', 'flag_code': 'af'},
    {'id': 'ku', 'name': 'Kurdish', 'flag': '🇮🇶', 'flag_code': 'iq'},
    {'id': 'az', 'name': 'Azerbaijani', 'flag': '🇦🇿', 'flag_code': 'az'},
    {'id': 'ka', 'name': 'Georgian', 'flag': '🇬🇪', 'flag_code': 'ge'},
    {'id': 'hy', 'name': 'Armenian', 'flag': '🇦🇲', 'flag_code': 'am'},
    {'id': 'uz', 'name': 'Uzbek', 'flag': '🇺🇿', 'flag_code': 'uz'},
    {'id': 'kk', 'name': 'Kazakh', 'flag': '🇰🇿', 'flag_code': 'kz'},
    {'id': 'ky', 'name': 'Kyrgyz', 'flag': '🇰🇬', 'flag_code': 'kg'},
    {'id': 'mn', 'name': 'Mongolian', 'flag': '🇲🇳', 'flag_code': 'mn'},
    {'id': 'my', 'name': 'Burmese', 'flag': '🇲🇲', 'flag_code': 'mm'},
    {'id': 'km', 'name': 'Khmer', 'flag': '🇰🇭', 'flag_code': 'kh'},
    {'id': 'lo', 'name': 'Lao', 'flag': '🇱🇦', 'flag_code': 'la'},
    {'id': 'ne', 'name': 'Nepali', 'flag': '🇳🇵', 'flag_code': 'np'},
    {'id': 'si', 'name': 'Sinhala', 'flag': '🇱🇰', 'flag_code': 'lk'},
    {'id': 'am', 'name': 'Amharic', 'flag': '🇪🇹', 'flag_code': 'et'},
    {'id': 'zu', 'name': 'Zulu', 'flag': '🇿🇦', 'flag_code': 'za'},
    {'id': 'xh', 'name': 'Xhosa', 'flag': '🇿🇦', 'flag_code': 'za'},
    {'id': 'yo', 'name': 'Yoruba', 'flag': '🇳🇬', 'flag_code': 'ng'},
    {'id': 'ig', 'name': 'Igbo', 'flag': '🇳🇬', 'flag_code': 'ng'},
    {'id': 'ha', 'name': 'Hausa', 'flag': '🇳🇬', 'flag_code': 'ng'},
]

# Complete list of all countries/nationalities with flag codes
# Format: {'id': 'iso_code (used as flag_code)', 'name': 'Nationality Name', 'flag': 'emoji'}
# Note: id is used directly as flag_code since they are always the same
PREDEFINED_NATIONALITIES = [
    {'id': 'af', 'name': 'Afghan', 'flag': '🇦🇫'},
    {'id': 'al', 'name': 'Albanian', 'flag': '🇦🇱'},
    {'id': 'dz', 'name': 'Algerian', 'flag': '🇩🇿'},
    {'id': 'ad', 'name': 'Andorran', 'flag': '🇦🇩'},
    {'id': 'ao', 'name': 'Angolan', 'flag': '🇦🇴'},
    {'id': 'ag', 'name': 'Antiguan', 'flag': '🇦🇬'},
    {'id': 'ar', 'name': 'Argentine', 'flag': '🇦🇷'},
    {'id': 'am', 'name': 'Armenian', 'flag': '🇦🇲'},
    {'id': 'au', 'name': 'Australian', 'flag': '🇦🇺'},
    {'id': 'at', 'name': 'Austrian', 'flag': '🇦🇹'},
    {'id': 'az', 'name': 'Azerbaijani', 'flag': '🇦🇿'},
    {'id': 'bs', 'name': 'Bahamian', 'flag': '🇧🇸'},
    {'id': 'bh', 'name': 'Bahraini', 'flag': '🇧🇭'},
    {'id': 'bd', 'name': 'Bangladeshi', 'flag': '🇧🇩'},
    {'id': 'bb', 'name': 'Barbadian', 'flag': '🇧🇧'},
    {'id': 'by', 'name': 'Belarusian', 'flag': '🇧🇾'},
    {'id': 'be', 'name': 'Belgian', 'flag': '🇧🇪'},
    {'id': 'bz', 'name': 'Belizean', 'flag': '🇧🇿'},
    {'id': 'bj', 'name': 'Beninese', 'flag': '🇧🇯'},
    {'id': 'bt', 'name': 'Bhutanese', 'flag': '🇧🇹'},
    {'id': 'bo', 'name': 'Bolivian', 'flag': '🇧🇴'},
    {'id': 'ba', 'name': 'Bosnian', 'flag': '🇧🇦'},
    {'id': 'bw', 'name': 'Motswana', 'flag': '🇧🇼'},
    {'id': 'br', 'name': 'Brazilian', 'flag': '🇧🇷'},
    {'id': 'bn', 'name': 'Bruneian', 'flag': '🇧🇳'},
    {'id': 'bg', 'name': 'Bulgarian', 'flag': '🇧🇬'},
    {'id': 'bf', 'name': 'Burkinabé', 'flag': '🇧🇫'},
    {'id': 'bi', 'name': 'Burundian', 'flag': '🇧🇮'},
    {'id': 'cv', 'name': 'Cape Verdean', 'flag': '🇨🇻'},
    {'id': 'kh', 'name': 'Cambodian', 'flag': '🇰🇭'},
    {'id': 'cm', 'name': 'Cameroonian', 'flag': '🇨🇲'},
    {'id': 'ca', 'name': 'Canadian', 'flag': '🇨🇦'},
    {'id': 'cf', 'name': 'Central African', 'flag': '🇨🇫'},
    {'id': 'td', 'name': 'Chadian', 'flag': '🇹🇩'},
    {'id': 'cl', 'name': 'Chilean', 'flag': '🇨🇱'},
    {'id': 'cn', 'name': 'Chinese', 'flag': '🇨🇳'},
    {'id': 'co', 'name': 'Colombian', 'flag': '🇨🇴'},
    {'id': 'km', 'name': 'Comoran', 'flag': '🇰🇲'},
    {'id': 'cg', 'name': 'Congolese', 'flag': '🇨🇬'},
    {'id': 'cd', 'name': 'Congolese (DRC)', 'flag': '🇨🇩'},
    {'id': 'cr', 'name': 'Costa Rican', 'flag': '🇨🇷'},
    {'id': 'ci', 'name': 'Ivorian', 'flag': '🇨🇮'},
    {'id': 'hr', 'name': 'Croatian', 'flag': '🇭🇷'},
    {'id': 'cu', 'name': 'Cuban', 'flag': '🇨🇺'},
    {'id': 'cy', 'name': 'Cypriot', 'flag': '🇨🇾'},
    {'id': 'cz', 'name': 'Czech', 'flag': '🇨🇿'},
    {'id': 'dk', 'name': 'Danish', 'flag': '🇩🇰'},
    {'id': 'dj', 'name': 'Djiboutian', 'flag': '🇩🇯'},
    {'id': 'dm', 'name': 'Dominican', 'flag': '🇩🇲'},
    {'id': 'do', 'name': 'Dominican', 'flag': '🇩🇴'},
    {'id': 'ec', 'name': 'Ecuadorian', 'flag': '🇪🇨'},
    {'id': 'eg', 'name': 'Egyptian', 'flag': '🇪🇬'},
    {'id': 'sv', 'name': 'Salvadoran', 'flag': '🇸🇻'},
    {'id': 'gq', 'name': 'Equatorial Guinean', 'flag': '🇬🇶'},
    {'id': 'er', 'name': 'Eritrean', 'flag': '🇪🇷'},
    {'id': 'ee', 'name': 'Estonian', 'flag': '🇪🇪'},
    {'id': 'sz', 'name': 'Swazi', 'flag': '🇸🇿'},
    {'id': 'et', 'name': 'Ethiopian', 'flag': '🇪🇹'},
    {'id': 'fj', 'name': 'Fijian', 'flag': '🇫🇯'},
    {'id': 'fi', 'name': 'Finnish', 'flag': '🇫🇮'},
    {'id': 'fr', 'name': 'French', 'flag': '🇫🇷'},
    {'id': 'ga', 'name': 'Gabonese', 'flag': '🇬🇦'},
    {'id': 'gm', 'name': 'Gambian', 'flag': '🇬🇲'},
    {'id': 'ge', 'name': 'Georgian', 'flag': '🇬🇪'},
    {'id': 'de', 'name': 'German', 'flag': '🇩🇪'},
    {'id': 'gh', 'name': 'Ghanaian', 'flag': '🇬🇭'},
    {'id': 'gr', 'name': 'Greek', 'flag': '🇬🇷'},
    {'id': 'gd', 'name': 'Grenadian', 'flag': '🇬🇩'},
    {'id': 'gt', 'name': 'Guatemalan', 'flag': '🇬🇹'},
    {'id': 'gn', 'name': 'Guinean', 'flag': '🇬🇳'},
    {'id': 'gw', 'name': 'Bissau-Guinean', 'flag': '🇬🇼'},
    {'id': 'gy', 'name': 'Guyanese', 'flag': '🇬🇾'},
    {'id': 'ht', 'name': 'Haitian', 'flag': '🇭🇹'},
    {'id': 'hn', 'name': 'Honduran', 'flag': '🇭🇳'},
    {'id': 'hu', 'name': 'Hungarian', 'flag': '🇭🇺'},
    {'id': 'is', 'name': 'Icelandic', 'flag': '🇮🇸'},
    {'id': 'in', 'name': 'Indian', 'flag': '🇮🇳'},
    {'id': 'id', 'name': 'Indonesian', 'flag': '🇮🇩'},
    {'id': 'ir', 'name': 'Iranian', 'flag': '🇮🇷'},
    {'id': 'iq', 'name': 'Iraqi', 'flag': '🇮🇶'},
    {'id': 'ie', 'name': 'Irish', 'flag': '🇮🇪'},
    {'id': 'il', 'name': 'Israeli', 'flag': '🇮🇱'},
    {'id': 'it', 'name': 'Italian', 'flag': '🇮🇹'},
    {'id': 'jm', 'name': 'Jamaican', 'flag': '🇯🇲'},
    {'id': 'jp', 'name': 'Japanese', 'flag': '🇯🇵'},
    {'id': 'jo', 'name': 'Jordanian', 'flag': '🇯🇴'},
    {'id': 'kz', 'name': 'Kazakhstani', 'flag': '🇰🇿'},
    {'id': 'ke', 'name': 'Kenyan', 'flag': '🇰🇪'},
    {'id': 'ki', 'name': 'I-Kiribati', 'flag': '🇰🇮'},
    {'id': 'kp', 'name': 'North Korean', 'flag': '🇰🇵'},
    {'id': 'kr', 'name': 'South Korean', 'flag': '🇰🇷'},
    {'id': 'kw', 'name': 'Kuwaiti', 'flag': '🇰🇼'},
    {'id': 'kg', 'name': 'Kyrgyzstani', 'flag': '🇰🇬'},
    {'id': 'la', 'name': 'Lao', 'flag': '🇱🇦'},
    {'id': 'lv', 'name': 'Latvian', 'flag': '🇱🇻'},
    {'id': 'lb', 'name': 'Lebanese', 'flag': '🇱🇧'},
    {'id': 'ls', 'name': 'Basotho', 'flag': '🇱🇸'},
    {'id': 'lr', 'name': 'Liberian', 'flag': '🇱🇷'},
    {'id': 'ly', 'name': 'Libyan', 'flag': '🇱🇾'},
    {'id': 'li', 'name': 'Liechtensteiner', 'flag': '🇱🇮'},
    {'id': 'lt', 'name': 'Lithuanian', 'flag': '🇱🇹'},
    {'id': 'lu', 'name': 'Luxembourgish', 'flag': '🇱🇺'},
    {'id': 'mg', 'name': 'Malagasy', 'flag': '🇲🇬'},
    {'id': 'mw', 'name': 'Malawian', 'flag': '🇲🇼'},
    {'id': 'my', 'name': 'Malaysian', 'flag': '🇲🇾'},
    {'id': 'mv', 'name': 'Maldivian', 'flag': '🇲🇻'},
    {'id': 'ml', 'name': 'Malian', 'flag': '🇲🇱'},
    {'id': 'mt', 'name': 'Maltese', 'flag': '🇲🇹'},
    {'id': 'mh', 'name': 'Marshallese', 'flag': '🇲🇭'},
    {'id': 'mr', 'name': 'Mauritanian', 'flag': '🇲🇷'},
    {'id': 'mu', 'name': 'Mauritian', 'flag': '🇲🇺'},
    {'id': 'mx', 'name': 'Mexican', 'flag': '🇲🇽'},
    {'id': 'fm', 'name': 'Micronesian', 'flag': '🇫🇲'},
    {'id': 'md', 'name': 'Moldovan', 'flag': '🇲🇩'},
    {'id': 'mc', 'name': 'Monégasque', 'flag': '🇲🇨'},
    {'id': 'mn', 'name': 'Mongolian', 'flag': '🇲🇳'},
    {'id': 'me', 'name': 'Montenegrin', 'flag': '🇲🇪'},
    {'id': 'ma', 'name': 'Moroccan', 'flag': '🇲🇦'},
    {'id': 'mz', 'name': 'Mozambican', 'flag': '🇲🇿'},
    {'id': 'mm', 'name': 'Myanmar', 'flag': '🇲🇲'},
    {'id': 'na', 'name': 'Namibian', 'flag': '🇳🇦'},
    {'id': 'nr', 'name': 'Nauruan', 'flag': '🇳🇷'},
    {'id': 'np', 'name': 'Nepalese', 'flag': '🇳🇵'},
    {'id': 'nl', 'name': 'Dutch', 'flag': '🇳🇱'},
    {'id': 'nz', 'name': 'New Zealander', 'flag': '🇳🇿'},
    {'id': 'ni', 'name': 'Nicaraguan', 'flag': '🇳🇮'},
    {'id': 'ne', 'name': 'Nigerien', 'flag': '🇳🇪'},
    {'id': 'ng', 'name': 'Nigerian', 'flag': '🇳🇬'},
    {'id': 'mk', 'name': 'Macedonian', 'flag': '🇲🇰'},
    {'id': 'no', 'name': 'Norwegian', 'flag': '🇳🇴'},
    {'id': 'om', 'name': 'Omani', 'flag': '🇴🇲'},
    {'id': 'pk', 'name': 'Pakistani', 'flag': '🇵🇰'},
    {'id': 'pw', 'name': 'Palauan', 'flag': '🇵🇼'},
    {'id': 'pa', 'name': 'Panamanian', 'flag': '🇵🇦'},
    {'id': 'pg', 'name': 'Papua New Guinean', 'flag': '🇵🇬'},
    {'id': 'py', 'name': 'Paraguayan', 'flag': '🇵🇾'},
    {'id': 'pe', 'name': 'Peruvian', 'flag': '🇵🇪'},
    {'id': 'ph', 'name': 'Filipino', 'flag': '🇵🇭'},
    {'id': 'pl', 'name': 'Polish', 'flag': '🇵🇱'},
    {'id': 'pt', 'name': 'Portuguese', 'flag': '🇵🇹'},
    {'id': 'qa', 'name': 'Qatari', 'flag': '🇶🇦'},
    {'id': 'ro', 'name': 'Romanian', 'flag': '🇷🇴'},
    {'id': 'ru', 'name': 'Russian', 'flag': '🇷🇺'},
    {'id': 'rw', 'name': 'Rwandan', 'flag': '🇷🇼'},
    {'id': 'kn', 'name': 'Kittitian', 'flag': '🇰🇳'},
    {'id': 'lc', 'name': 'Saint Lucian', 'flag': '🇱🇨'},
    {'id': 'vc', 'name': 'Vincentian', 'flag': '🇻🇨'},
    {'id': 'ws', 'name': 'Samoan', 'flag': '🇼🇸'},
    {'id': 'sm', 'name': 'Sammarinese', 'flag': '🇸🇲'},
    {'id': 'st', 'name': 'São Toméan', 'flag': '🇸🇹'},
    {'id': 'sa', 'name': 'Saudi Arabian', 'flag': '🇸🇦'},
    {'id': 'sn', 'name': 'Senegalese', 'flag': '🇸🇳'},
    {'id': 'rs', 'name': 'Serbian', 'flag': '🇷🇸'},
    {'id': 'sc', 'name': 'Seychellois', 'flag': '🇸🇨'},
    {'id': 'sl', 'name': 'Sierra Leonean', 'flag': '🇸🇱'},
    {'id': 'sg', 'name': 'Singaporean', 'flag': '🇸🇬'},
    {'id': 'sk', 'name': 'Slovak', 'flag': '🇸🇰'},
    {'id': 'si', 'name': 'Slovenian', 'flag': '🇸🇮'},
    {'id': 'sb', 'name': 'Solomon Islander', 'flag': '🇸🇧'},
    {'id': 'so', 'name': 'Somali', 'flag': '🇸🇴'},
    {'id': 'za', 'name': 'South African', 'flag': '🇿🇦'},
    {'id': 'ss', 'name': 'South Sudanese', 'flag': '🇸🇸'},
    {'id': 'es', 'name': 'Spanish', 'flag': '🇪🇸'},
    {'id': 'lk', 'name': 'Sri Lankan', 'flag': '🇱🇰'},
    {'id': 'sd', 'name': 'Sudanese', 'flag': '🇸🇩'},
    {'id': 'sr', 'name': 'Surinamese', 'flag': '🇸🇷'},
    {'id': 'se', 'name': 'Swedish', 'flag': '🇸🇪'},
    {'id': 'ch', 'name': 'Swiss', 'flag': '🇨🇭'},
    {'id': 'sy', 'name': 'Syrian', 'flag': '🇸🇾'},
    {'id': 'tw', 'name': 'Taiwanese', 'flag': '🇹🇼'},
    {'id': 'tj', 'name': 'Tajikistani', 'flag': '🇹🇯'},
    {'id': 'tz', 'name': 'Tanzanian', 'flag': '🇹🇿'},
    {'id': 'th', 'name': 'Thai', 'flag': '🇹🇭'},
    {'id': 'tl', 'name': 'Timorese', 'flag': '🇹🇱'},
    {'id': 'tg', 'name': 'Togolese', 'flag': '🇹🇬'},
    {'id': 'to', 'name': 'Tongan', 'flag': '🇹🇴'},
    {'id': 'tt', 'name': 'Trinidadian', 'flag': '🇹🇹'},
    {'id': 'tn', 'name': 'Tunisian', 'flag': '🇹🇳'},
    {'id': 'tr', 'name': 'Turkish', 'flag': '🇹🇷'},
    {'id': 'tm', 'name': 'Turkmen', 'flag': '🇹🇲'},
    {'id': 'tv', 'name': 'Tuvaluan', 'flag': '🇹🇻'},
    {'id': 'ug', 'name': 'Ugandan', 'flag': '🇺🇬'},
    {'id': 'ua', 'name': 'Ukrainian', 'flag': '🇺🇦'},
    {'id': 'ae', 'name': 'Emirati', 'flag': '🇦🇪'},
    {'id': 'gb', 'name': 'British', 'flag': '🇬🇧'},
    {'id': 'us', 'name': 'American', 'flag': '🇺🇸'},
    {'id': 'uy', 'name': 'Uruguayan', 'flag': '🇺🇾'},
    {'id': 'uz', 'name': 'Uzbekistani', 'flag': '🇺🇿'},
    {'id': 'vu', 'name': 'Vanuatuan', 'flag': '🇻🇺'},
    {'id': 'va', 'name': 'Vatican', 'flag': '🇻🇦'},
    {'id': 've', 'name': 'Venezuelan', 'flag': '🇻🇪'},
    {'id': 'vn', 'name': 'Vietnamese', 'flag': '🇻🇳'},
    {'id': 'ye', 'name': 'Yemeni', 'flag': '🇾🇪'},
    {'id': 'zm', 'name': 'Zambian', 'flag': '🇿🇲'},
    {'id': 'zw', 'name': 'Zimbabwean', 'flag': '🇿🇼'},
    # Special territories and regions
    {'id': 'hk', 'name': 'Hong Konger', 'flag': '🇭🇰'},
    {'id': 'mo', 'name': 'Macanese', 'flag': '🇲🇴'},
    {'id': 'ps', 'name': 'Palestinian', 'flag': '🇵🇸'},
    {'id': 'gf', 'name': 'French Guianese', 'flag': '🇬🇫'},
    {'id': 'pf', 'name': 'French Polynesian', 'flag': '🇵🇫'},
    {'id': 'nc', 'name': 'New Caledonian', 'flag': '🇳🇨'},
    {'id': 're', 'name': 'Réunionese', 'flag': '🇷🇪'},
    {'id': 'pr', 'name': 'Puerto Rican', 'flag': '🇵🇷'},
    {'id': 'gu', 'name': 'Guamanian', 'flag': '🇬🇺'},
    {'id': 'as', 'name': 'American Samoan', 'flag': '🇦🇸'},
    {'id': 'vi', 'name': 'U.S. Virgin Islander', 'flag': '🇻🇮'},
    {'id': 'mp', 'name': 'Northern Mariana Islander', 'flag': '🇲🇵'},
    {'id': 'fo', 'name': 'Faroese', 'flag': '🇫🇴'},
    {'id': 'gl', 'name': 'Greenlandic', 'flag': '🇬🇱'},
    {'id': 'ax', 'name': 'Åland Islander', 'flag': '🇦🇽'},
    {'id': 'gi', 'name': 'Gibraltarian', 'flag': '🇬🇮'},
    {'id': 'je', 'name': 'Jersey', 'flag': '🇯🇪'},
    {'id': 'gg', 'name': 'Guernsey', 'flag': '🇬🇬'},
    {'id': 'im', 'name': 'Manx', 'flag': '🇮🇲'},
    {'id': 'ky', 'name': 'Caymanian', 'flag': '🇰🇾'},
    {'id': 'fk', 'name': 'Falkland Islander', 'flag': '🇫🇰'},
    {'id': 'bm', 'name': 'Bermudian', 'flag': '🇧🇲'},
    {'id': 'vg', 'name': 'British Virgin Islander', 'flag': '🇻🇬'},
    {'id': 'tc', 'name': 'Turks and Caicos Islander', 'flag': '🇹🇨'},
    {'id': 'ai', 'name': 'Anguillan', 'flag': '🇦🇮'},
    {'id': 'ms', 'name': 'Montserratian', 'flag': '🇲🇸'},
    {'id': 'sh', 'name': 'Saint Helenian', 'flag': '🇸🇭'},
    {'id': 'pn', 'name': 'Pitcairn Islander', 'flag': '🇵🇳'},
    {'id': 'gs', 'name': 'South Georgian', 'flag': '🇬🇸'},
    {'id': 'io', 'name': 'British Indian Ocean Territory', 'flag': '🇮🇴'},
]

# Predefined categories with IDs for filtering
PREDEFINED_CATEGORIES = [
    {'id': 'life_coaching', 'name': 'Life Coaching'},
    {'id': 'career_coaching', 'name': 'Career Coaching'},
    {'id': 'business_coaching', 'name': 'Business Coaching'},
    {'id': 'health_coaching', 'name': 'Health Coaching'},
    {'id': 'wellness_coaching', 'name': 'Wellness Coaching'},
    {'id': 'fitness_coaching', 'name': 'Fitness Coaching'},
    {'id': 'nutrition_coaching', 'name': 'Nutrition Coaching'},
    {'id': 'relationship_coaching', 'name': 'Relationship Coaching'},
    {'id': 'executive_coaching', 'name': 'Executive Coaching'},
    {'id': 'performance_coaching', 'name': 'Performance Coaching'},
    {'id': 'leadership_coaching', 'name': 'Leadership Coaching'},
    {'id': 'mindfulness_coaching', 'name': 'Mindfulness Coaching'},
    {'id': 'spiritual_coaching', 'name': 'Spiritual Coaching'},
    {'id': 'financial_coaching', 'name': 'Financial Coaching'},
    {'id': 'time_management_coaching', 'name': 'Time Management Coaching'},
    {'id': 'personal_development_coaching', 'name': 'Personal Development Coaching'},
    {'id': 'confidence_coaching', 'name': 'Confidence Coaching'},
    {'id': 'communication_coaching', 'name': 'Communication Coaching'},
    {'id': 'public_speaking_coaching', 'name': 'Public Speaking Coaching'},
    {'id': 'sales_coaching', 'name': 'Sales Coaching'},
    {'id': 'marketing_coaching', 'name': 'Marketing Coaching'},
    {'id': 'entrepreneurship_coaching', 'name': 'Entrepreneurship Coaching'},
    {'id': 'startup_coaching', 'name': 'Startup Coaching'},
    {'id': 'productivity_coaching', 'name': 'Productivity Coaching'},
    {'id': 'stress_management_coaching', 'name': 'Stress Management Coaching'},
    {'id': 'work_life_balance_coaching', 'name': 'Work-Life Balance Coaching'},
    {'id': 'parenting_coaching', 'name': 'Parenting Coaching'},
    {'id': 'dating_coaching', 'name': 'Dating Coaching'},
    {'id': 'marriage_coaching', 'name': 'Marriage Coaching'},
    {'id': 'grief_coaching', 'name': 'Grief Coaching'},
    {'id': 'recovery_coaching', 'name': 'Recovery Coaching'},
    {'id': 'addiction_recovery_coaching', 'name': 'Addiction Recovery Coaching'},
    {'id': 'weight_loss_coaching', 'name': 'Weight Loss Coaching'},
    {'id': 'yoga_coaching', 'name': 'Yoga Coaching'},
    {'id': 'meditation_coaching', 'name': 'Meditation Coaching'},
    {'id': 'holistic_health_coaching', 'name': 'Holistic Health Coaching'},
    {'id': 'mental_health_coaching', 'name': 'Mental Health Coaching'},
    {'id': 'financial_coaching', 'name': 'Financial Coaching'},
    {'id': 'investment_coaching', 'name': 'Investment Coaching'},
    {'id': 'retirement_coaching', 'name': 'Retirement Coaching'},
    {'id': 'career_transition_coaching', 'name': 'Career Transition Coaching'},
    {'id': 'job_search_coaching', 'name': 'Job Search Coaching'},
    {'id': 'interview_coaching', 'name': 'Interview Coaching'},
    {'id': 'resume_coaching', 'name': 'Resume Coaching'},
    {'id': 'linkedin_coaching', 'name': 'LinkedIn Coaching'},
    {'id': 'branding_coaching', 'name': 'Branding Coaching'},
    {'id': 'online_presence_coaching', 'name': 'Online Presence Coaching'},
    {'id': 'crisis_management_coaching', 'name': 'Crisis Management Coaching'},
    {'id': 'change_management_coaching', 'name': 'Change Management Coaching'},
    {'id': 'team_coaching', 'name': 'Team Coaching'},
    {'id': 'organizational_coaching', 'name': 'Organizational Coaching'},
    {'id': 'culture_coaching', 'name': 'Culture Coaching'},
    {'id': 'diversity_inclusion_coaching', 'name': 'Diversity & Inclusion Coaching'},
    {'id': 'women_leadership_coaching', 'name': 'Women in Leadership Coaching'},
    {'id': 'executive_presence_coaching', 'name': 'Executive Presence Coaching'},
    {'id': 'influence_coaching', 'name': 'Influence & Persuasion Coaching'},
    {'id': 'negotiation_coaching', 'name': 'Negotiation Coaching'},
    {'id': 'innovation_coaching', 'name': 'Innovation Coaching'},
    {'id': 'creativity_coaching', 'name': 'Creativity Coaching'},
    {'id': 'design_thinking_coaching', 'name': 'Design Thinking Coaching'},
    {'id': 'agile_coaching', 'name': 'Agile Coaching'},
    {'id': 'lean_startup_coaching', 'name': 'Lean Startup Coaching'},
    {'id': 'growth_coaching', 'name': 'Growth Coaching'},
    {'id': 'content_strategy_coaching', 'name': 'Content Strategy Coaching'},
    {'id': 'customer_experience_coaching', 'name': 'Customer Experience Coaching'},
    {'id': 'product_development_coaching', 'name': 'Product Development Coaching'},
    {'id': 'data_analysis_coaching', 'name': 'Data Analysis Coaching'},
    {'id': 'presentation_coaching', 'name': 'Presentation Coaching'},
    {'id': 'storytelling_coaching', 'name': 'Storytelling Coaching'},
]

# Common timezones grouped by region for user-friendly selection
# Format: {'id': 'IANA_timezone', 'name': 'Display Name', 'region': 'Region Name', 'offset': 'UTC offset'}
COMMON_TIMEZONES = [
    # North America
    {'id': 'America/New_York', 'name': 'Eastern Time (US & Canada)', 'region': 'North America', 'offset': 'UTC-5'},
    {'id': 'America/Chicago', 'name': 'Central Time (US & Canada)', 'region': 'North America', 'offset': 'UTC-6'},
    {'id': 'America/Denver', 'name': 'Mountain Time (US & Canada)', 'region': 'North America', 'offset': 'UTC-7'},
    {'id': 'America/Los_Angeles', 'name': 'Pacific Time (US & Canada)', 'region': 'North America', 'offset': 'UTC-8'},
    {'id': 'America/Phoenix', 'name': 'Arizona', 'region': 'North America', 'offset': 'UTC-7'},
    {'id': 'America/Anchorage', 'name': 'Alaska', 'region': 'North America', 'offset': 'UTC-9'},
    {'id': 'Pacific/Honolulu', 'name': 'Hawaii', 'region': 'North America', 'offset': 'UTC-10'},
    {'id': 'America/Toronto', 'name': 'Eastern Time (Canada)', 'region': 'North America', 'offset': 'UTC-5'},
    {'id': 'America/Vancouver', 'name': 'Pacific Time (Canada)', 'region': 'North America', 'offset': 'UTC-8'},
    {'id': 'America/Mexico_City', 'name': 'Mexico City', 'region': 'North America', 'offset': 'UTC-6'},
    
    # Europe
    {'id': 'Europe/London', 'name': 'London', 'region': 'Europe', 'offset': 'UTC+0'},
    {'id': 'Europe/Paris', 'name': 'Paris', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Berlin', 'name': 'Berlin', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Rome', 'name': 'Rome', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Madrid', 'name': 'Madrid', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Amsterdam', 'name': 'Amsterdam', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Brussels', 'name': 'Brussels', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Vienna', 'name': 'Vienna', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Zurich', 'name': 'Zurich', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Stockholm', 'name': 'Stockholm', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Oslo', 'name': 'Oslo', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Copenhagen', 'name': 'Copenhagen', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Helsinki', 'name': 'Helsinki', 'region': 'Europe', 'offset': 'UTC+2'},
    {'id': 'Europe/Warsaw', 'name': 'Warsaw', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Prague', 'name': 'Prague', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Budapest', 'name': 'Budapest', 'region': 'Europe', 'offset': 'UTC+1'},
    {'id': 'Europe/Athens', 'name': 'Athens', 'region': 'Europe', 'offset': 'UTC+2'},
    {'id': 'Europe/Lisbon', 'name': 'Lisbon', 'region': 'Europe', 'offset': 'UTC+0'},
    {'id': 'Europe/Dublin', 'name': 'Dublin', 'region': 'Europe', 'offset': 'UTC+0'},
    {'id': 'Europe/Moscow', 'name': 'Moscow', 'region': 'Europe', 'offset': 'UTC+3'},
    {'id': 'Europe/Kiev', 'name': 'Kyiv', 'region': 'Europe', 'offset': 'UTC+2'},
    {'id': 'Europe/Istanbul', 'name': 'Istanbul', 'region': 'Europe', 'offset': 'UTC+3'},
    
    # Asia Pacific
    {'id': 'Asia/Dubai', 'name': 'Dubai', 'region': 'Middle East', 'offset': 'UTC+4'},
    {'id': 'Asia/Riyadh', 'name': 'Riyadh', 'region': 'Middle East', 'offset': 'UTC+3'},
    {'id': 'Asia/Jerusalem', 'name': 'Jerusalem', 'region': 'Middle East', 'offset': 'UTC+2'},
    {'id': 'Asia/Tehran', 'name': 'Tehran', 'region': 'Middle East', 'offset': 'UTC+3:30'},
    {'id': 'Asia/Kolkata', 'name': 'Mumbai, New Delhi', 'region': 'Asia', 'offset': 'UTC+5:30'},
    {'id': 'Asia/Dhaka', 'name': 'Dhaka', 'region': 'Asia', 'offset': 'UTC+6'},
    {'id': 'Asia/Bangkok', 'name': 'Bangkok', 'region': 'Asia', 'offset': 'UTC+7'},
    {'id': 'Asia/Singapore', 'name': 'Singapore', 'region': 'Asia', 'offset': 'UTC+8'},
    {'id': 'Asia/Hong_Kong', 'name': 'Hong Kong', 'region': 'Asia', 'offset': 'UTC+8'},
    {'id': 'Asia/Shanghai', 'name': 'Beijing, Shanghai', 'region': 'Asia', 'offset': 'UTC+8'},
    {'id': 'Asia/Tokyo', 'name': 'Tokyo', 'region': 'Asia', 'offset': 'UTC+9'},
    {'id': 'Asia/Seoul', 'name': 'Seoul', 'region': 'Asia', 'offset': 'UTC+9'},
    {'id': 'Asia/Manila', 'name': 'Manila', 'region': 'Asia', 'offset': 'UTC+8'},
    {'id': 'Asia/Jakarta', 'name': 'Jakarta', 'region': 'Asia', 'offset': 'UTC+7'},
    {'id': 'Asia/Kuala_Lumpur', 'name': 'Kuala Lumpur', 'region': 'Asia', 'offset': 'UTC+8'},
    {'id': 'Asia/Taipei', 'name': 'Taipei', 'region': 'Asia', 'offset': 'UTC+8'},
    {'id': 'Asia/Sydney', 'name': 'Sydney', 'region': 'Asia Pacific', 'offset': 'UTC+10'},
    {'id': 'Australia/Melbourne', 'name': 'Melbourne', 'region': 'Asia Pacific', 'offset': 'UTC+10'},
    {'id': 'Australia/Brisbane', 'name': 'Brisbane', 'region': 'Asia Pacific', 'offset': 'UTC+10'},
    {'id': 'Pacific/Auckland', 'name': 'Auckland', 'region': 'Asia Pacific', 'offset': 'UTC+12'},
    
    # South America
    {'id': 'America/Sao_Paulo', 'name': 'São Paulo', 'region': 'South America', 'offset': 'UTC-3'},
    {'id': 'America/Buenos_Aires', 'name': 'Buenos Aires', 'region': 'South America', 'offset': 'UTC-3'},
    {'id': 'America/Lima', 'name': 'Lima', 'region': 'South America', 'offset': 'UTC-5'},
    {'id': 'America/Bogota', 'name': 'Bogotá', 'region': 'South America', 'offset': 'UTC-5'},
    {'id': 'America/Santiago', 'name': 'Santiago', 'region': 'South America', 'offset': 'UTC-3'},
    {'id': 'America/Caracas', 'name': 'Caracas', 'region': 'South America', 'offset': 'UTC-4'},
    
    # Africa
    {'id': 'Africa/Cairo', 'name': 'Cairo', 'region': 'Africa', 'offset': 'UTC+2'},
    {'id': 'Africa/Johannesburg', 'name': 'Johannesburg', 'region': 'Africa', 'offset': 'UTC+2'},
    {'id': 'Africa/Lagos', 'name': 'Lagos', 'region': 'Africa', 'offset': 'UTC+1'},
    {'id': 'Africa/Nairobi', 'name': 'Nairobi', 'region': 'Africa', 'offset': 'UTC+3'},
    {'id': 'Africa/Casablanca', 'name': 'Casablanca', 'region': 'Africa', 'offset': 'UTC+1'},
    
    # UTC
    {'id': 'UTC', 'name': 'UTC (Coordinated Universal Time)', 'region': 'UTC', 'offset': 'UTC+0'},
]
