# Predefined mentor types for autocomplete suggestions
PREDEFINED_MENTOR_TYPES = [
    'Life Coach',
    'Career Coach',
    'Business Coach',
    'Health Coach',
    'Wellness Coach',
    'Fitness Coach',
    'Nutrition Coach',
    'Relationship Coach',
    'Executive Coach',
    'Performance Coach',
    'Leadership Coach',
    'Mindfulness Coach',
    'Spiritual Coach',
    'Financial Coach',
    'Time Management Coach',
]

# Predefined tags for filtering mentors
PREDEFINED_TAGS = [
    'Leadership',
    'Communication',
    'Time Management',
    'Goal Setting',
    'Stress Management',
    'Career Development',
    'Business Strategy',
    'Marketing',
    'Sales',
    'Team Building',
    'Conflict Resolution',
    'Public Speaking',
    'Productivity',
    'Work-Life Balance',
    'Confidence Building',
    'Networking',
    'Personal Branding',
    'Financial Planning',
    'Health & Wellness',
    'Nutrition',
    'Fitness',
    'Mental Health',
    'Mindfulness',
    'Meditation',
    'Relationships',
    'Dating',
    'Parenting',
    'Life Transitions',
    'Retirement Planning',
    'Entrepreneurship',
    'Startup',
    'Scaling Business',
    'Digital Marketing',
    'Social Media',
    'Content Creation',
    'Writing',
    'Coaching',
    'Mentoring',
    'Training',
    'Workshop Facilitation',
]

# Predefined languages with IDs for filtering
PREDEFINED_LANGUAGES = [
    {'id': 'en', 'name': 'English'},
    {'id': 'es', 'name': 'Spanish'},
    {'id': 'fr', 'name': 'French'},
    {'id': 'de', 'name': 'German'},
    {'id': 'it', 'name': 'Italian'},
    {'id': 'pt', 'name': 'Portuguese'},
    {'id': 'ru', 'name': 'Russian'},
    {'id': 'zh', 'name': 'Chinese'},
    {'id': 'ja', 'name': 'Japanese'},
    {'id': 'ko', 'name': 'Korean'},
    {'id': 'ar', 'name': 'Arabic'},
    {'id': 'hi', 'name': 'Hindi'},
    {'id': 'nl', 'name': 'Dutch'},
    {'id': 'sv', 'name': 'Swedish'},
    {'id': 'pl', 'name': 'Polish'},
    {'id': 'cs', 'name': 'Czech'},
    {'id': 'tr', 'name': 'Turkish'},
    {'id': 'vi', 'name': 'Vietnamese'},
    {'id': 'th', 'name': 'Thai'},
    {'id': 'he', 'name': 'Hebrew'},
    {'id': 'uk', 'name': 'Ukrainian'},
    {'id': 'ro', 'name': 'Romanian'},
    {'id': 'hu', 'name': 'Hungarian'},
    {'id': 'fi', 'name': 'Finnish'},
    {'id': 'da', 'name': 'Danish'},
    {'id': 'no', 'name': 'Norwegian'},
    {'id': 'el', 'name': 'Greek'},
    {'id': 'bg', 'name': 'Bulgarian'},
    {'id': 'hr', 'name': 'Croatian'},
    {'id': 'sk', 'name': 'Slovak'},
    {'id': 'sl', 'name': 'Slovenian'},
    {'id': 'sr', 'name': 'Serbian'},
    {'id': 'et', 'name': 'Estonian'},
    {'id': 'lv', 'name': 'Latvian'},
    {'id': 'lt', 'name': 'Lithuanian'},
    {'id': 'id', 'name': 'Indonesian'},
    {'id': 'ms', 'name': 'Malay'},
    {'id': 'tl', 'name': 'Tagalog'},
    {'id': 'sw', 'name': 'Swahili'},
    {'id': 'af', 'name': 'Afrikaans'},
    {'id': 'ca', 'name': 'Catalan'},
    {'id': 'eu', 'name': 'Basque'},
    {'id': 'ga', 'name': 'Irish'},
    {'id': 'mt', 'name': 'Maltese'},
    {'id': 'is', 'name': 'Icelandic'},
    {'id': 'mk', 'name': 'Macedonian'},
    {'id': 'sq', 'name': 'Albanian'},
    {'id': 'bs', 'name': 'Bosnian'},
    {'id': 'bn', 'name': 'Bengali'},
    {'id': 'ta', 'name': 'Tamil'},
    {'id': 'te', 'name': 'Telugu'},
    {'id': 'mr', 'name': 'Marathi'},
    {'id': 'gu', 'name': 'Gujarati'},
    {'id': 'kn', 'name': 'Kannada'},
    {'id': 'ml', 'name': 'Malayalam'},
    {'id': 'pa', 'name': 'Punjabi'},
    {'id': 'ur', 'name': 'Urdu'},
    {'id': 'fa', 'name': 'Persian'},
    {'id': 'ps', 'name': 'Pashto'},
    {'id': 'ku', 'name': 'Kurdish'},
    {'id': 'az', 'name': 'Azerbaijani'},
    {'id': 'ka', 'name': 'Georgian'},
    {'id': 'hy', 'name': 'Armenian'},
    {'id': 'uz', 'name': 'Uzbek'},
    {'id': 'kk', 'name': 'Kazakh'},
    {'id': 'ky', 'name': 'Kyrgyz'},
    {'id': 'mn', 'name': 'Mongolian'},
    {'id': 'my', 'name': 'Burmese'},
    {'id': 'km', 'name': 'Khmer'},
    {'id': 'lo', 'name': 'Lao'},
    {'id': 'ne', 'name': 'Nepali'},
    {'id': 'si', 'name': 'Sinhala'},
    {'id': 'am', 'name': 'Amharic'},
    {'id': 'zu', 'name': 'Zulu'},
    {'id': 'xh', 'name': 'Xhosa'},
    {'id': 'yo', 'name': 'Yoruba'},
    {'id': 'ig', 'name': 'Igbo'},
    {'id': 'ha', 'name': 'Hausa'},
]

# Predefined categories with IDs for filtering
PREDEFINED_CATEGORIES = [
    {'id': 'life_coaching', 'name': 'Life Coaching'},
    {'id': 'career_coaching', 'name': 'Career Coaching'},
    {'id': 'business_coaching', 'name': 'Business Coaching'},
    {'id': 'health_coaching', 'name': 'Health Coaching'},
    {'id': 'wellness_coaching', 'name': 'Wellness Coaching'},
    {'id': 'fitness_coaching', 'name': 'Fitness Coaching'},
    {'id': 'nutrition_coaching', 'name': 'Nutrition Coaching'},
    {'id': 'relationship_coaching', 'name': 'Relationship Coaching'},
    {'id': 'executive_coaching', 'name': 'Executive Coaching'},
    {'id': 'performance_coaching', 'name': 'Performance Coaching'},
    {'id': 'leadership_coaching', 'name': 'Leadership Coaching'},
    {'id': 'mindfulness_coaching', 'name': 'Mindfulness Coaching'},
    {'id': 'spiritual_coaching', 'name': 'Spiritual Coaching'},
    {'id': 'financial_coaching', 'name': 'Financial Coaching'},
    {'id': 'time_management_coaching', 'name': 'Time Management Coaching'},
]

# First session free options
FIRST_SESSION_FREE_CHOICES = [
    ('no', 'No'),
    ('15', '15 minutes'),
    ('20', '20 minutes'),
    ('25', '25 minutes'),
    ('30', '30 minutes'),
    ('35', '35 minutes'),
    ('40', '40 minutes'),
    ('45', '45 minutes'),
    ('50', '50 minutes'),
    ('55', '55 minutes'),
    ('60', '60 minutes'),
]

