from django.urls import path
from . import views
from general import views as general_views

app_name = "dashboard_mentor"

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('account/', views.account, name='account'),
    path('profile/', views.profile, name='profile'),
    path('settings/', views.settings_view, name='settings'),
    path('support/', views.support_view, name='support'),
    path('billing/', views.billing, name='billing'),
    path('my-sessions/', views.my_sessions, name='my_sessions'),
    path('my-sessions/get-availability/', views.get_availability, name='get_availability'),
    path('my-sessions/check-collisions/', views.check_availability_collisions, name='check_availability_collisions'),
    path('my-sessions/save-availability/', views.save_availability, name='save_availability'),
    path('my-sessions/client-suggestions/', views.client_suggestions, name='client_suggestions'),
    path('my-sessions/delete-availability-slot/', views.delete_availability_slot, name='delete_availability_slot'),
    path('clients/', views.clients_list, name='clients_list'),
    path('clients/<int:client_id>/', views.client_detail, name='client_detail'),
    path('clients/<int:client_id>/request-review/', views.request_review, name='request_review'),
    path('invite-client/', views.invite_client, name='invite_client'),
    path('my-sessions/invite-session/', views.invite_session, name='invite_session'),
    path('my-sessions/schedule-session/', views.schedule_session, name='schedule_session'),
    path('my-sessions/remind-session/', views.remind_session, name='remind_session'),
    path('my-sessions/refund-session/', views.refund_session, name='refund_session'),
    path('my-sessions/session/<int:session_id>/', views.session_detail, name='session_detail'),
    path('my-sessions/get-sessions/', views.get_sessions_paginated, name='get_sessions_paginated'),
    path('dashboard/upcoming-sessions/', views.get_dashboard_upcoming_sessions, name='get_dashboard_upcoming_sessions'),
    path('clients/<int:relationship_id>/resend/', views.resend_client_invitation, name='resend_client_invitation'),
    path('clients/<int:relationship_id>/delete/', views.delete_client_relationship, name='delete_client_relationship'),
    path('notifications/', general_views.notification_list, name='notification_list'),
    path('notifications/<int:notification_id>/', general_views.notification_detail, name='notification_detail'),
    path('notifications/<int:notification_id>/mark-read/', general_views.notification_mark_read, name='notification_mark_read'),
    path('notifications/mark-all-read/', general_views.notification_mark_all_read, name='notification_mark_all_read'),
    path('notifications/<int:notification_id>/modal/', general_views.notification_modal_detail, name='notification_modal_detail'),
    path('tickets/<int:ticket_id>/', views.ticket_detail, name='ticket_detail'),
    path('blog/', views.blog_list, name='blog_list'),
    path('blog/create/', views.blog_create, name='blog_create'),
    path('blog/<int:post_id>/edit/', views.blog_edit, name='blog_edit'),
    path('blog/<int:post_id>/delete/', views.blog_delete, name='blog_delete'),
    path('profile/reviews/', views.reviews_management, name='reviews_management'),
    path('reviews/<int:review_id>/reply/', views.review_reply, name='review_reply'),
    path('reviews/secure/<str:uidb64>/<str:token>/', views.view_reviews_secure, name='view_reviews_secure'),
    path('clients/api/', views.clients_api, name='clients_api'),
    path('projects/templates/api/', views.project_templates_api, name='project_templates_api'),
    path('projects/modules/api/', views.project_modules_api, name='project_modules_api'),
    path('projects/create/', views.create_project, name='create_project'),
    path('templates/', views.templates_list, name='templates_list'),
    path('templates/create/', views.create_custom_template, name='create_custom_template'),
    path('projects/', views.projects_list, name='projects_list'),
    path('projects/<int:project_id>/', views.project_detail, name='project_detail'),
    path('projects/<int:project_id>/stages/create/', views.create_stage, name='create_stage'),
    path('projects/<int:project_id>/stages/generate-ai/', views.generate_stages_ai, name='generate_stages_ai'),
    path('projects/<int:project_id>/stages/<int:stage_id>/', views.stage_detail, name='stage_detail'),
    path('projects/<int:project_id>/stages/<int:stage_id>/edit/', views.edit_stage, name='edit_stage'),
    path('projects/<int:project_id>/stages/<int:stage_id>/confirm/', views.confirm_stage, name='confirm_stage'),
    path('projects/<int:project_id>/stages/<int:stage_id>/delete/', views.delete_stage, name='delete_stage'),
    path('projects/<int:project_id>/stages/<int:stage_id>/update-dates/', views.update_stage_dates, name='update_stage_dates'),
    path('projects/<int:project_id>/stages/<int:stage_id>/tasks/create/', views.create_task, name='create_task'),
    path('projects/<int:project_id>/stages/<int:stage_id>/tasks/generate-ai/', views.generate_tasks_ai, name='generate_tasks_ai'),
    path('projects/<int:project_id>/stages/<int:stage_id>/tasks/api/', views.get_tasks_api, name='get_tasks_api'),
    path('projects/<int:project_id>/stages/<int:stage_id>/tasks/<int:task_id>/toggle-complete/', views.toggle_task_complete, name='toggle_task_complete'),
    path('projects/<int:project_id>/stages/<int:stage_id>/tasks/<int:task_id>/delete/', views.delete_task, name='delete_task'),
    path('projects/<int:project_id>/stages/reorder/', views.reorder_stages, name='reorder_stages'),
    path('projects/<int:project_id>/stages/api/', views.get_stages_api, name='get_stages_api'),
]

